### ISSUE TITLE
investigate and improve university Student Loan Default Rate viz

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1000]

**Comment by azapatam** [comment]
It's done!

The viz used a data call that cut across similar universities. The ids of these universities came from a variable in a generator obtained from the `ipeds_completions` cube.

The cube used in this chart is `ed_defaults` and it does not have the same list of institutions as `ipeds_completions`. Then, when one of the ids in the list was not in the cube, the entire query returned empty.

I tried to create a generator that would return similar ids based on the `ed_defaults` cube, but this cube has `OPEID` as drilldown and not `University ID` and calling neighbors doesn't work.

So to fix it, I made 5 data calls on viz creation, one for each neighbor, and concatenated the data. So by concatenating, you get all the necessary values. If one of the institutions does not exist, it simply does not provide data and will not be in the final result.

Before
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/42551166/191350765-60ba918d-abf0-42c0-a253-dc4b0036417e.png">

After
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/42551166/191350501-945b6985-d760-474c-804b-f2cf04856d50.png">

**Comment by davelandry** [comment]
great investigation and fix here @azapatam!

one question: can you determine of the bug of "include a non-valid member ID to kill the data" is happening at the `canon-logiclayer` level or at the `mondrian-rest` level? If it's in `canon`, we might be able to patch it and go back down to 1 URL... but if it's mondrian then forget about it!

**Comment by azapatam** [comment]
I'm not familiar with `mondrian-rest,` how can I check it?

**Comment by davelandry** [comment]
Use the `mondrian-rest-ui`, the grandfather to `tesseract-ui` 👴🏻 

https://wad-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJPUEVJRCIsIk9QRUlEIiwiT1BFSUQiXV0sImN1dHMiOltdLCJjdWJlIjoiZWRfZGVmYXVsdHMiLCJtZWFzdXJlcyI6WyJCb3Jyb3dlcnMgSW4gRGVmYXVsdCJdfQ==

(click "Debug" in the top-right to view the API url)
