### ISSUE TITLE
N/A year in Children in Poverty Nation report

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1008]
https://wad.datausa.io/profile/geo/united-states#children_in_poverty

<img width="1218" alt="Screen Shot 2022-10-26 at 12 19 29 PM" src="https://user-images.githubusercontent.com/1847581/198066802-257dfdb0-d00c-4787-a9e3-d1c31341bcd3.png">

**Comment by azapatam** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/42551166/199992547-d3c72690-0db2-4d51-b2c4-4d01380edb32.png)
