### ISSUE TITLE
many N/As on very small profiles

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1009]
I found two good examples for testing small locations:
* https://wad.datausa.io/profile/geo/kalawao-county-hi
* any Puerto Rico profile 😅 

Most of these pages have dozens of N/As, and I would guess that we just need to hide content here when it does not exist.

**Comment by azapatam** [comment]
`kalawao-county-hi` now has no N/A

**Comment by azapatam** [comment]
I randomly checked 10 Puerto Rico counties/places and after changing some visibility logics, there is no N/A anymore.
`(Working in my local)`
