### ISSUE TITLE
N/As in Admissions and Tuition

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1010]
This might be a case where a location had no IPEDS data?
* https://wad.datausa.io/profile/geo/santa-ana-city-east-puma-ca#admissions_applicants_enrolled
* https://wad.datausa.io/profile/geo/santa-ana-city-east-puma-ca#district_tuition

**Comment by azapatam** [comment]
I've checked the cubes and there's no data for this place.
New visibility logic hides charts anywhere if there is no data to display. 
`(Working in my local)`
