### ISSUE TITLE
N/As and broken chart in Presidential Popular Vote by County section of Los Angeles County profile

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1013]
https://wad.datausa.io/profile/geo/los-angeles-county-ca#civics

The chart is stuck at "Loading", there are 4 N/As in the paragraph, and I believe those 4 N/As are also repeated in the Civics Grouping text as well.

**Comment by azapatam** [comment]
That chart shouldn't have been active at the county level....
