### ISSUE TITLE
N/As and broken text in Concentrations section

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1014]
https://wad.datausa.io/profile/geo/dale-city-lake-ridge-woodbridge-puma-va#majors

- [x] When there are < 3 majors, N/As show up in the second stat (allowed?)
- [x] `degree-majorss` should probably be `degree-majors`, and then the variable will work (I remember this one happening because of an incorrect SQL statement change a long time ago)

**Comment by azapatam** [comment]
Done!
