### ISSUE TITLE
N/As and errors in Education Population section of multi-state PUMAs

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1015]
https://wad.datausa.io/profile/geo/new-york-newark-jersey-city-ny-nj-pa#population-education

**Comment by azapatam** [comment]
It is not a problem of multi-state PUMAs, there is simply no data for New York-Newark-Jersey City, NY-NJ-PA in the `pums_5` cube.

I will hide the section in these cases.

**Comment by azapatam** [comment]
There is no data for MSA and in the hierarchies it is not possible to associate an MSA to a State.

The option is to hide the section for MSAs

**Comment by davelandry** [comment]
@azapatam incorrect 😏 the node logiclayer is actually able to bubble up an MSA to a State, or sometimes _multiple_ states, as is the case in some of our Civics charts: https://datausa.io/profile/geo/new-york-newark-jersey-city-ny-nj-pa#president-popular

It can sometimes be a little complicated to juggle the multiple states, so it's okay to remove some complex stuff if needed 😅
