### ISSUE TITLE
errors in Tuition by Sector section for locations with only 1 University

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1016]
https://wad.datausa.io/profile/geo/spring-valley-summerlin-south-puma-nv#district_tuition

**Comment by azapatam** [comment]
I have hidden the paragraphs when there is `N/A`, but in this graph there is data depending on the option selected in the selector: there is data for State Tuition but not for State Fee. In my opinion, it is not bad to have a graph without data, finally that is a data, right? (No State Fee data available for the selected location)... but if you want to hide the entire section in this case, I can do it.

**Comment by davelandry** [comment]
🤔 I wonder if we could try/do 2 things:
 - make the State Tuition and State Fees data be stacked bars in the same chart, so that the total bar size is `tuition + fees` for each sector. This would make us have to put the sector labels on the y-axis, which may _destroy_ the chart, so maybe this won't work?
 - hide the first selector if "All" is the only option

This also makes me think about bringing in all of the other variables that factor into "Average Net Price", such as books, room and board, and supplies: https://nces.ed.gov/ipeds/report-your-data/faq-average-net-price

I'm not sure if we have those data points at the granularity we need here, but I cold see those other costs being part of the "stack" of each bar, and then we could even have a part of each bar going "negative" to the left to show the average cost of grants/aid (because then that chart would be showing how they calculate "average net price")

**Comment by azapatam** [comment]
I'd say it's possible, I'll try in the afternoon.

Regarding the selector, by default the selector should not appear if there is only one option available... is there any additional configuration missing in canon-cms or another library?

**Comment by davelandry** [comment]
🤦🏻 duh, that's the logic I'm fixing in my selector branch jajaja

**Comment by azapatam** [comment]
@davelandry, these are the available measures, can you tell me which ones should be in the stacked bars? For now I have Tuition, Fee and Books & Supplies... I'm not very familiar with this topic so any help is welcome.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/42551166/203410157-d32dfc31-188a-4d16-b603-8bdaadf1d810.png">

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/42551166/203411027-58090e09-7779-46e8-a9fc-d0e123f1540d.png">

**Comment by azapatam** [comment]
And in another cube we have the measure `Median Grant Or Scholarship Award` but it is not disaggregated by sectors or geography.

**Comment by davelandry** [comment]
From what I can see, I think those 3 are perfect 👍🏻 

Looks amazing @azapatam! 😍
