### ISSUE TITLE
Radar chart not drawing on load

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#102]
Doesn't seem to happen on every page, but on the Physicians and Surgeons page the radar chart of skills sometimes doesn't draw when the page first loads.

http://beta.datausa.io/profile/soc/291060/#skills

If you toggle to view by RCA it starts working. Also if you refresh the pages 3-5 times you see if works sometimes as well.

**Comment by davelandry** [comment]
@jspeis I just did a couple of Radar bug fixes (like #61) and I'm now not able to reproduce this bug. when you get a chance, can you help me try to recreate it? it may be fixed, but I want to be sure.

**Comment by jspeis** [comment]
Not able to reproduce, looks good!
