### ISSUE TITLE
is there a better way to label the different advanced search filter depths?

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#106]
from Peter:
> In the search results and navigation pane on the left, the ‘four-digit’, ‘three’digit’, and ‘top-level’ labels are hard for most users to understand.  Could you please think about the best way from a customer experience perspective to convey this choice?  What you’re really saying is, most specific/detailed, most general, and so forth, correct?  How can you present this more transparently?

**Comment by alexandersimoes** [comment]
Yes there is a better way:

NAICS (from [wikipedia](https://en.wikipedia.org/wiki/North_American_Industry_Classification_System)):
* sector
* subsector
* industry group

SOC (from [BLS](http://www.bls.gov/soc/2000/socguide.htm):
* major group
* minor group
* broad occupation
* detailed occupation

I was unable to find anything better for CIP besides just saying how many digits deep the code is.
