### ISSUE TITLE
fix IP address showing in View Data URL and homepage Share image

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#1124]

**Comment by nspmx** [comment]
Harcoded host value at NGINX level to map prod host as the used value at Virew Data component

ref:
- https://github.com/Datawheel/canon/blob/master/packages/cms/src/components/Viz/Options.jsx#L375
- https://github.com/Datawheel/canon/blob/master/packages/core/src/server.jsx#L52-L73
