### ISSUE TITLE
ACS retail trade labelling issue

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#136]
http://beta.datausa.io/profile/geo/16000US1714000/economy/tmap_ind_num_emp/

This treemap shows motor vehicle parts dealers are 8.9% of Chicago industrial employment but that does not appear in the ACS data:
http://api.censusreporter.org/1.0/data/show/acs2013_5yr?table_ids=C24030&geo_ids=16000US1714000

(Via Danny Bachman)

**Comment by alexandersimoes** [comment]
officially RESOLVED :-) see the b4 & after below:

**b4:**
![screen shot 2016-01-04 at 4 12 43 pm](https://cloud.githubusercontent.com/assets/252276/12100764/ec1d1b06-b2fe-11e5-83a6-6ea7cfdec943.png)

**after**
![screen shot 2016-01-04 at 4 12 47 pm](https://cloud.githubusercontent.com/assets/252276/12100765/ec1d8c6c-b2fe-11e5-9473-700d27c3ce13.png)
