### ISSUE TITLE
acs_5yr.ygl_speakers has duplicate values

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#144]
year	geo	language	num_speakers	num_speakers_moe	num_speakers_rca
2013	01000US	002	2.31123e+08	108816	1
2014	01000US	002	2.31123e+08	108816	1
2013	01000US	002	2.31123e+08	108816	1
2014	01000US	002	2.31123e+08	108816	1

looks like there are repeated values in acs_5yr.ygl_speakers, also want to confirm that values are ok too

**Comment by alexandersimoes** [comment]
Ended up re-running the ygl_speakers script and this resolved the issue. I assume it was run twice be accident.

Here's a check in SQL in case this happens again:
```sql
select year, geo, language, count(*) from acs_5yr.ygl_speakers group by year, geo, language having count(*) > 1;
```

**Comment by davelandry** [comment]
is it feasible for us to have a test script which runs a set of of assertions for all of the tables? I'm familiar with JS libraries that do this, so I'm assuming there's probably a standard Python test library everybody uses.

**Comment by jspeis** [comment]
definitely a good idea and definitely feasible!

**Comment by davelandry** [comment]
@jspeis :beers:
