### ISSUE TITLE
NYC population different from Wikipedia

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#156]
The Wikipedia article for NYC conflicts with the stated 8.27M people who live in NYC and it uses ACS data as the source https://en.wikipedia.org/wiki/Demographics_of_New_York_City 

![image](https://cloud.githubusercontent.com/assets/3857364/12128692/f695fc14-b3cc-11e5-8500-3e699852d401.png)

I suspect this is due to my prior issue on which data set we are calling to make that calculation.

**Comment by jspeis** [comment]
8.27M was the 2013 1-year estimate, when we release tonight we'll have the 2014 data estimating 8.49M people
