### ISSUE TITLE
RCA relabeling

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#157]
Can we norm the RCA so that its central point is 0? I don't think anyone knows what it means but I think people will be more likely to know that positive means more than expected and negative means less.

**Comment by davelandry** [comment]
I think that goes against all of the previous work and publications regarding RCA, but I'll let @alexandersimoes and @cesifoti be the deciding factor here

**Comment by danielbyler** [comment]
My concern isn't the 0 or the 1 as much a that it's not clear what it means if you don't know what RCA is and (more importantly) where to go if you have no idea what it means

**Comment by cesifoti** [comment]
RCA has many names (Relative Risk in medicine, Lift in CS), so I am not
married to the name. One more intuitive way of calling this is "Over or
Under Expression," but it is a mouthful. So I am open to suggestions, but
it has to be a good one.



*__________________**________*
César A. Hidalgo | @cesifoti
<http://t.sidekickopen32.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbv3xVd0vTb1q7bXCVQsyTK56dzx7f7WRD6s02?t=http%3A%2F%2Ftwitter.com%2Fcesifoti&si=5860908454903808&pi=d8d5d27d-0bf6-4118-d431-afcee1af5afc>

Associate Professor, The MIT Media Lab,
Massachusetts Institute of Technology (MIT)
http://www.chidalgo.com | http://macro.media.mit.edu
<http://macroconnections.media.mit.edu>

Do you know Why Information Grows
<http://t.sidekickopen32.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbv3xVd0vTb1q7bXCVQsyTK56dzx7f7WRD6s02?t=http%3A%2F%2Fwww.amazon.com%2FWhy-Information-Grows-Evolution-Economies%2Fdp%2F0465048994&si=5860908454903808&pi=d8d5d27d-0bf6-4118-d431-afcee1af5afc>
?

**Comment by davelandry** [comment]
@cesifoti the discussion here is about changing the over/under number from 1 to 0

**Comment by cesifoti** [comment]
It is a ratio, so 0 to 1 does not work. In logs, it is from -inf to +inf
with the middle in 0. In linear scale, it is from 1/n to n with the middle
in 1.

*__________________**________*
César A. Hidalgo | @cesifoti
<http://t.sidekickopen32.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbv3xVd0vTb1q7bXCVQsyTK56dzx7f7WRD6s02?t=http%3A%2F%2Ftwitter.com%2Fcesifoti&si=5860908454903808&pi=9c8b9ce4-9635-468a-c3ef-6a921573f0d7>

Associate Professor, The MIT Media Lab,
Massachusetts Institute of Technology (MIT)
http://www.chidalgo.com | http://macro.media.mit.edu
<http://macroconnections.media.mit.edu>

Do you know Why Information Grows
<http://t.sidekickopen32.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbv3xVd0vTb1q7bXCVQsyTK56dzx7f7WRD6s02?t=http%3A%2F%2Fwww.amazon.com%2FWhy-Information-Grows-Evolution-Economies%2Fdp%2F0465048994&si=5860908454903808&pi=9c8b9ce4-9635-468a-c3ef-6a921573f0d7>
?
