### ISSUE TITLE
Wage Text

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#158]
Wage and income may not be the same thing (have to check) because I think income can include non-wage items like welfare. 

Additionally, the header is average wage but the data is median and that's not the same. 

Similarly, the 'on average' sentence could just be replaced with 'The typical person in XXX had an income of YYY.' The stat above is clearly labeled as median income but I think something like that would be clearer.

**Comment by danielbyler** [comment]
![image](https://cloud.githubusercontent.com/assets/3857364/12128897/26aafe62-b3ce-11e5-9475-158460db21ae.png)

**Comment by davelandry** [comment]
I can make this change, but I defer to @jspeis before doing it. He's very familiar with the different "universes" each dataset lives in.

**Comment by jspeis** [comment]
Just checked ACS, that value represents the median household income. 

cc @alexandersimoes

**Comment by davelandry** [comment]
this is now "median household income", as confirmed by @alexandersimoes
