### ISSUE TITLE
associates degrees in IPEDS

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#165]
Does the IPEDS data have categories that are like 'associate degree'? I'm just surprised I don't see any people in the workforce with that degree. 

![image](https://cloud.githubusercontent.com/assets/3857364/12205223/486c3ee0-b607-11e5-87a1-8208c64e367c.png)

**Comment by jspeis** [comment]
Workforce related education data comes from PUMS. PUMS data only captures the major for bachelor's degrees or higher. Therefore we would not be able to see the number of people with associates degrees who studied X in the workforce from PUMS data (again, we can see it around around variables like geography, industry or occupation - just not major). So for the workplace comparisons based around a major we might only want to show bachelors & higher and perhaps separately show the the other levels of educational attainment from IPEDS separately.

**Comment by danielbyler** [comment]
Ah that makes total sense. We need to segregate that graph then (I think we talked about this a long time ago but briefly) otherwise the impression we are giving is not correct. Maybe we just contrast among the education levels we have the data and split the 'below college' degrees into a second chart below or right beside it?

**Comment by davelandry** [comment]
oooooo I like the idea of a second smaller miniviz underneath the paragraph

I'll put this on my plate, and yell over to @jspeis if/when I need help hooking it up

**Comment by davelandry** [comment]
Alright guys, so the miniviz is pretty illegible and seems out of place, but removing the extra columns helps a ton. You'll see this in Thursday's update.
