### ISSUE TITLE
Question on sorting

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#168]
Are locations sorted by population? This doesn't seem like it is and I'm curious

![image](https://cloud.githubusercontent.com/assets/3857364/12237356/4125c452-b84c-11e5-9fe8-ee2a4d7bfd59.png)

**Comment by davelandry** [comment]
The search results use a custom "z-score" based on an algorithm which uses a topic-specific variable to assign weight/order. I'll let @jspeis explain it better, but I do believe we use population for locations.

**Comment by jspeis** [comment]
The sorting works on an algorithm that takes into account a location's population relative to other locations at it's geographic level (using the z-score of the location's population for its geographic level). So in this instance it means that Columbus the place is larger relative to other places than the Columbus Metro Area compared to other metro areas
