### ISSUE TITLE
Skills radar diagram seems to be broken

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#169]
The shape of the radar diagram appears to be the same for all education profiles:
http://beta.datausa.io/profile/cip/513801/#skills

**Comment by davelandry** [comment]
I'll take a look into this.

**Comment by davelandry** [comment]
@pviechnicki they skills radar is drawing correctly given the data from O*NET. For example, the General Chemistry (http://beta.datausa.io/profile/cip/400501/skills/radar/) radar shows much less manual labor skills than the Lineworkers (http://beta.datausa.io/profile/cip/460303/skills/radar/) radar.

In general, it seems that most courses require at least some proficiency in basic skills like reading, writing, etc.
