### ISSUE TITLE
hierarchical display for search results

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#171]
In the search results pane, right now we see 2-digit, 3-digit, 4-digit level entities.  Is it possible to nest these and show a plus sign, so that you can easily zero in on the level of abstraction that you want?

**Comment by alexandersimoes** [comment]
Just to clarify are you saying that by default we would have just the main profile categories shown ie locations, industries, occupation and education with a + (plus) sign to drill deeper?
