### ISSUE TITLE
Why does the 4-digit accounting profile page state that it is showing data for business degrees?

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#172]
Is this by design?  I found it confusing.

http://beta.datausa.io/profile/cip/5203/#industries

**Comment by jspeis** [comment]
Our PUMS datasets only contain data to the 2-digit CIP code equivalent since that is the only level at which the Census provides a crosswalk from PUMS' field of degree to CIP, so instead of showing no data we show data for the parent.
