### ISSUE TITLE
intput/output broken

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#174]
No matter where I click on the right hand side, I get this message 

![image](https://cloud.githubusercontent.com/assets/3857364/12277352/e5b358ca-b948-11e5-8097-091da436de7a.png)

**Comment by davelandry** [comment]
@danielbyler, can you send me the specific profile you are seeing this error on? I'm not able to reproduce this.

**Comment by danielbyler** [comment]
Sorry, I forget :(

**Comment by davelandry** [comment]
No worries, I'm going to close this issue because I've done a lot of fixes/improvements to the sankey which probably fixed this.

However, if you are able to reproduce this sometime down the road, open it back up!
