### ISSUE TITLE
what happened to the list of STEM majors?

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#176]
Can we use the STEM/Non-STEM field to filter the education profiles?  I know you guys had found a list of STEM majors, but where are we using it in the interface?

Thanks,
-Peter

**Comment by davelandry** [comment]
We're currently not using it anywhere in the interface. Two ideas we've had:
* Denote a STEM major on the profile's splash page somehow (badge, text, etc).
* Allow filtering the advanced search to only show STEM majors.

The only caveat is that we only have STEM/Non-STEM status for the deepest (6-digit) courses. We're assuming that STEM status would not bubble up to the parents, but can you clarify that for us?
