### ISSUE TITLE
Manufacturing number doesn't match

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#177]
BLS cites manufacturing employment at 12 million http://www.bls.gov/iag/tgs/iag31-33.htm . Can you please confirm this total of 15M is correct http://beta.datausa.io/profile/naics/31-33/ ?

**Comment by davelandry** [comment]
@danielbyler, did you mean to close this issue? were you able to find the discrepancy?

**Comment by davelandry** [comment]
ohps, I see #178 now
