### ISSUE TITLE
map bug with Alaska zoom

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#179]
<img width="1071" alt="screenshot 2016-01-13 21 34 07" src="https://cloud.githubusercontent.com/assets/8160651/12312354/8474f6b8-ba3d-11e5-8b17-cac58d27690a.png">

wonky loading (broken images near the bottom) in the geomap where window is narrow

**Comment by zwhitman** [comment]
Suggestion on this - how about we lose the aleutian chain? these base layers can break along the dateline which zooms out the extent, and given the map div height sizing, you're always going to spill out into the southern nothingness.

**Comment by davelandry** [comment]
@zwhitman, you read my mind :beers: 

p.s. I might be able to translate the map to the right ever so slightly so that it doesn't get wrapped, so I'm going to try that first
