### ISSUE TITLE
change geo map color gradient

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#180]
Can we make it so that high income is blue, not red? It's just not intuitive. 

http://beta.datausa.io/profile/geo/16000US5462140/

![image](https://cloud.githubusercontent.com/assets/3857364/12330480/604d4b7a-bab3-11e5-9573-e3d4faaf0720.png)

**Comment by davelandry** [comment]
In most cases that I've seen, red usually implies the greater value in heat maps. We were originally inspired by the heat maps commonly produced by MatLab: https://www.google.com/search?q=matlab+heatmap&safe=off&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiEseiOsbbKAhWJdz4KHQOGCjYQ_AUIBygB&biw=1280&bih=1356#imgrc=_

It may be that the intermediate colors are confusing, what if we were to go from blue to grey to red? Also want to bring @melteng in on this conversation.

**Comment by melteng** [comment]
Yep, I agree with @danielbyler - for this viz, I'd imagine red to signify lower wages. I'm looking into the color schemes for all the profile visualizations to make them more intuitive individually and consistent collectively. To remove the good v. bad connotations involving color, I'll likely make the geomap color scale a light > dark gradient.

**Comment by alexandersimoes** [comment]
I dislike the idea of using a monochrome color scale for the purpose of heatmaps since it hinders legibility IMHO. Thinking of the above map it would be hard to differentiate say light blue from a shade slightly lighter or darker for very small areas whereas I can see quite distinctly the diff between green and yellow even tho they are adjacent to each other on the value scale.

**Comment by TroyBishop** [comment]
Agree with Dan. The color coding on the map is not intuitive; red = danger, stop, warning, negative. Consider limited hues (e.g. grays and blues) and tints of those hues; lighter tints = less concentration, darker tints = higher concentrations. Also, you will get more aesthetic harmony with more tints of fewer hues.

**Comment by zwhitman** [comment]
Also want to point out that the map color scale is not good for colorblind folks.

Normal:
![image](https://cloud.githubusercontent.com/assets/5577360/13475038/b38d1ea4-e08e-11e5-974d-16f9e37f5d83.png)

Colorblind:
![image](https://cloud.githubusercontent.com/assets/5577360/13475059/ce262abc-e08e-11e5-80c1-481be41da4f3.png)

**Comment by davelandry** [comment]
@melteng and myself have spent the last few days trying out a range of different color scales. We tried both monochromatic and dichromatic color scales, but found that given the white from the "no-data" sections, we were limited in the range of values we could articulate with these color scales. After all of our tests, we found that a scale with multiple colors -- specifically from a dark blue to yellow to red -- is the best scale to express both broad range of values and the nuances between close values.

We recognize that people will associate certain colors with certain meanings, but given that we're using the same scale for dozens of different topics, it becomes very difficult to find a universal solution void of meaning.

To take into account accessibility for red/green color blind, we removed green (thanks @zwhitman). We also increased the general opacity and decreased stroke opacity to improve overall legibility. With all of these tweaks, we feel that the maps are now much more legible. Here are some before and afters of our new proposal:

<img width="1027" alt="screen shot 2016-03-10 at 11 25 07 am" src="https://cloud.githubusercontent.com/assets/1847581/13676900/ad037fd8-e6b5-11e5-818a-ec61208b33ce.png">

<img width="1027" alt="screen shot 2016-03-10 at 11 25 21 am" src="https://cloud.githubusercontent.com/assets/1847581/13676901/b146893c-e6b5-11e5-93dd-0169edf35c4c.png">

<img width="763" alt="screen shot 2016-03-10 at 11 25 30 am" src="https://cloud.githubusercontent.com/assets/1847581/13676906/b5b605a6-e6b5-11e5-80ab-d823a4f80073.png">

<img width="762" alt="screen shot 2016-03-10 at 11 25 40 am" src="https://cloud.githubusercontent.com/assets/1847581/13676912/b85927ca-e6b5-11e5-8523-341949e9efd5.png">

**Comment by davelandry** [comment]
with the addition of color breaks (#190) we're working on a new monochromatic color scale. here's a work in progress preview:

![data usa - map of median age by county](https://cloud.githubusercontent.com/assets/1847581/16596984/882326f8-42c4-11e6-8b39-b83fdd145693.png)

**Comment by zwhitman** [comment]
awesome
