### ISSUE TITLE
X-axis labels on income distribution bar graphs missing

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#181]
What happened to the x-axis labels on the income distribution bar graphs?  They seem to be all missing.  For example:

http://beta.datausa.io/profile/soc/291141/#employment

I've noticed the same problem on some of the other bar graphs.  Can you check all the profiles and make sure they're all labeled?

**Comment by davelandry** [comment]
@pviechnicki, what operating system (Windows 7, Windows 8, etc) and browser are you using?

**Comment by davelandry** [comment]
seems to be an issue with Firefox
