### ISSUE TITLE
icon & color attr missing from "Education and Interdisciplinary Studies"

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#183]
CIP degrees
id: 30
display: MULTI/INTERDISCIPLINARY STUDIES

see Houston, TX for example

(in screenshot, I've isolated just this degree in the treemap)
<img width="1377" alt="screenshot 2016-01-15 00 55 27" src="https://cloud.githubusercontent.com/assets/8160651/12345060/ed83caea-bb22-11e5-8683-85e2d3b707ba.png">

**Comment by davelandry** [comment]
@melteng, I can reproduce this. Can you try to replicate this and see if it still persists?

**Comment by davelandry** [comment]
it might be a weird local cache thing, also try typing this into your console and then reloading the page:
```js
localforage.clear()
```
