### ISSUE TITLE
map sidepanel for additional information

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#188]
## Suggestion

I think we have an opportunity to present a cut-down version of a profile page as a sidepanel when a geography is selected

**Comment by zwhitman** [comment]
want to bring this to your attention - prob discussion point tomorrow. might be good to hop on a quick call to discuss a few of the map items.

**Comment by davelandry** [comment]
there's a lot of good ideas to improve the map, we just need to prioritize what's feasible given the remaining time

**Comment by zwhitman** [comment]
ok - we'll discuss on group call tomorrow but we need to make sure the map allows us to jump into location profile pages. This would be the point of the sidebar

**Comment by davelandry** [comment]
click to zoom with new sidepanel containing clickable name link to profile and top 10 children as clickable links (still designing, but functionally working):
<img width="1279" alt="screen shot 2016-02-09 at 5 53 52 pm" src="https://cloud.githubusercontent.com/assets/1847581/12933474/2e8b800e-cf56-11e5-9e92-d046dbec9cf0.png">
