### ISSUE TITLE
main menu slide-in animation choppy on map page

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#189]
Sidebar animation gets pretty choppy at lower geographies. you save a ton of bandwidth using topo but i've found that the conversion back to geojson can cause a laggy experience on weaker machines. could we explore shipping geojson to save on client-side processing?

**Comment by davelandry** [comment]
it's my understanding that once the coordinates have been plotted to paths in the DOM, there's really no difference whether they come from topojson or geojson, so the file format/conversion shouldn't be interfering with any other page elements (regardless of format).

do you mean the side menu? the one you get to by clicking on the "hamburger" menu in the top left? can you post your browser/system specs? I'm having trouble recreating the choppiness

**Comment by zwhitman** [comment]
Yes sorry i'm talking about the side menu. Also sorry for the vague report. It's choppy in Chrome, buttery in Firefox, and totally unworkable/freezes in IE.

Browsers:
Chrome: 47.0.2526.106 m
Firefox: 43.0.2
IE: 11

Win 8.1 Enterprise
Processor: i7-4600U @ 2.10/2.70
Ram: 16gb

**Comment by davelandry** [comment]
@zwhitman can you confirm whether or not this issue still exists?

**Comment by davelandry** [comment]
@zwhitman *poke*
