### ISSUE TITLE
map breaks

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#190]
I think we need to take a close look at break logic. We have a lot of circumstances where the map differences aren't illustrated and you basically get a single color. There's a few options we may want to consider (or maybe offer break controls, eg. jenks vs quantile etc)

![image](https://cloud.githubusercontent.com/assets/5577360/12556668/149f9f2a-c355-11e5-8bbb-b5403ed05695.png)

**Comment by davelandry** [comment]
I think this might actually be a data issue and not a break issue. When looking at specifically "Graduate Growth" I noticed that the percentages look very strange.

@zwhitman, have you noticed any other data points that map like this?

@jspeis, can you take a look into the graduate growth numbers?

**Comment by jspeis** [comment]
The API call was previously returning data by county, by course instead of just data by county - this issue is fixed. Here's what the map looks like now:

<img width="729" alt="screen shot 2016-01-26 at 9 01 55 am" src="https://cloud.githubusercontent.com/assets/87581/12582527/bb3bd32e-c40b-11e5-8c08-5915c56ea61a.png">

**Comment by davelandry** [comment]
@jspeis :+1:

@zwhitman I worry that if we change the scale/breaks between each different dataset, it might mislead the user. I always tend to err on the side of consistency

**Comment by zwhitman** [comment]
Sorry for the huge delay. Homeowners, Citizens, Homicide rate, Population, and Degrees awarded are pretty homogeneous - i think we may need to figure out how we want to rep these data. should we ramp the scale or apply breaks?

**Comment by zwhitman** [comment]
I'm having a really hard time discerning between values with the color ramp and I think binning values with jenks natural breaks would be easier to understand. For example, are there any differences between north dakota/nebraska/kansas/colorado here? I think wisconsin is higher than iowa and missouri but that could be the borders playing tricks on me. Also, not sure if wisconsin is closer to 40.1 or 43.5. 

It also might help to adjust the scales based on what's in view to extenuate the differences.

![image](https://cloud.githubusercontent.com/assets/5577360/13475306/1732b134-e090-11e5-9be1-0307ac3c7085.png)

**Comment by davelandry** [comment]
I totally agree that we should change the color scale (#180), but changing the underlying scale logic from a continuous scale to a bucketed scale this close to release might create more unforeseen problems/bugs than we have time to fix.

I'll try a couple of "Hail Marys" this week, but if it gets too hairy I'm going to pull back and push this to 2.0

**Comment by zwhitman** [comment]
word. I'd say this is def a priority because it's apparent right away with the initial map view but i understand we're close. let me know if there's anything i can do to help

**Comment by davelandry** [comment]
Next Thursday's update will include color breaks based on this research paper: https://journal.r-project.org/archive/2011-2/RJournal_2011-2_Wang+Song.pdf

Using this Javascript library: http://simplestatistics.org/docs/#ckmeans
