### ISSUE TITLE
move map controls out of header

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#194]
I think we might want to move the map controls out of the header. suggest either across the top or fix on left side. that way there's consistent experience with the header across the site.

**Comment by davelandry** [comment]
Marking this as resolved, as for now they have a different background color (still considering moving them though).

**Comment by zwhitman** [comment]
I still think we need a background color behind the entire legend (white with like 80% transparency). When the legend is above the choropleth, the scale becomes very difficult to see.

**Comment by davelandry** [comment]
Great point, I've made a new issue for that: #219
