### ISSUE TITLE
only outlines showing for county geography in health data

### ISSUE THREAD

**Issue by alexandersimoes** [DataUSA/datausa-site#197]
![screen shot 2016-01-25 at 6 44 56 pm](https://cloud.githubusercontent.com/assets/252276/12568426/d4a2ade2-c393-11e5-8b8d-14715b636907.png)

http://beta.datausa.io/profile/geo/16000US3570700/health/crime/

**Comment by davelandry** [comment]
was an issue with the intro geo map's CSS overwriting the viz styles
