### ISSUE TITLE
commute time shows "N/A"

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#200]
Looking at the Santa Teresa NM profile, the commute time section makes little sense and needs improvement.  It says something like, the commute time is NA (I don't have the exact text).  If no data's available, then different auto text should be used.
For the graphs on commute time and transport mode, they need legends.  Can you add those?

**Comment by davelandry** [comment]
@alexandersimoes is looking into the data being "N/A", and I've created a separate issue for the legend: #204

**Comment by alexandersimoes** [comment]
This is caused by there being no data for table B08136 "Aggregate Travel Time to Work (In Minutes) of Workers by Means of Transportation to Work". If we instead use B08013 "Aggregate Travel Time to Work (In Minutes) of Workers by Sex" this issue will be resolved. Working on it now...

**Comment by alexandersimoes** [comment]
FIXED!

![screen shot 2016-02-09 at 4 30 02 pm](https://cloud.githubusercontent.com/assets/252276/12931182/6c6a01fe-cf4a-11e5-9909-e1240887fd37.png)

**Comment by davelandry** [comment]
:beers:
