### ISSUE TITLE
GINI description inverted

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#206]
"New York, NY has an income GINI of 0.506. That is higher than the national average of 0.485. In other words, wages are distributed more evenly in New York, NY when comparing to the national average."

This should read

"New York, NY has an income GINI of 0.506. That is higher than the national average of 0.485. In other words, wages are distributed **less** evenly in New York, NY when comparing to the national average."

**Comment by davelandry** [comment]
good catch :+1:
