### ISSUE TITLE
Still missing x axis labels on Industry profile, wages by gender chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#208]
for example:
http://beta.datausa.io/profile/naics/2213M/#workforce.

Also, can you label this chart so that it's clear you're showing the top 5 occupations within the industry?  Otherwise it's confusing.  I thought I was looking at 5 income brackets, not five occupations.

**Comment by davelandry** [comment]
A label for this chart is a good idea.

Can you upload a screenshot of you're missing x-axis labels? At least what browser and operating system you're seeing it in?

**Comment by pviechnicki** [comment]
It looks like this is working in the latest push.  I was using chrome.

**Comment by davelandry** [comment]
@pviechnicki :+1:
