### ISSUE TITLE
Embed link not working as expected on industry profile

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#209]
I was doing a demo of the 'Water, steam, air conditioning and irrigation' industry and wanted to demo embedding the wages by gender chart.  When I tried to open the embed link in a new tab, it just takes me to the top of the profile page again, not to the specific chart.  Not sure if this is a general issue, or specific to this chart, or user error.

**Comment by davelandry** [comment]
Can you describe/recreate the exact steps that lead you to this problem? When clicking on the embed icon, a text box should appear with the new link inside of it. The expected behavior is to click the link, copy it, and then paste it into a new window/tab.

**Comment by pviechnicki** [comment]
I open the profile for water, steam, air-conditioning, and irrigation systems. Scroll to Wages by gender.  Click the embed link.  I get a weird tool tip, partially cut off, which only contains http://beta,dataus (sic).  Then I can't get rid of the tool tip.  Then I reload the page.  Then I right click the embed icon, and it gives me a link to this url: http://beta.datausa.io/profile/naics/2213M/#.  When I open this in a new tab, it has me back up at the top of the profile, not the specific visualization I'm trying to embed.

**Comment by davelandry** [comment]
When you click the embed link, what appears is not a tooltip but a text box. It's cut off visually, but it does actually contain the entire link. When you click on that text box, it will automatically select the entire text link, and then you can copy and paste that into a new tab.

**Comment by davelandry** [comment]
@pviechnicki I'm going to mark this as closed. Let me know if you have any more questions about this (since the behavior on the site has now changed).
