### ISSUE TITLE
GINI labelling on Geo profiles

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#211]
In the [income distribution section](http://beta.datausa.io/profile/geo/16000US2507000/economy/income_distro/) we show the GINI, however the GINI is computed from PUMS (versus the rest of the viz which comes from regular ACS estimates) and second the PUMS GINI may or may not cover the same geography depending on the profile page.

**Comment by davelandry** [comment]
Edits to both the subtitle and the paragraph text. Here's the page for Boston, MA:
<img width="463" alt="screen shot 2016-02-10 at 4 24 27 pm" src="https://cloud.githubusercontent.com/assets/1847581/12962289/d64c7dfe-d012-11e5-9132-bbe587cf4e1e.png">
