### ISSUE TITLE
auto-text incorrect on citizenship bar graph

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#212]
The auto-text for the citizenship bar graph for Connecticut is wrong.  Both bars are 92.9%, but the auto text says that CT is lower than the national average.
http://beta.datausa.io/profile/geo/connecticut/#demographics

**Comment by davelandry** [comment]
This is an issue where the numbers were REALLY close (but not equal), and the rounding we do on the front end was making them look the same. Here's our solution:

<img width="419" alt="screen shot 2016-02-10 at 4 01 29 pm" src="https://cloud.githubusercontent.com/assets/1847581/12961655/b1df90b2-d00f-11e5-93d2-eb1ffd964991.png">
