### ISSUE TITLE
Rank of earnings by education

### ISSUE THREAD

**Issue by DannyBachman** [DataUSA/datausa-site#215]
Tells me Philosophy is the 14th earning major of 1,416. But I don't know what the 1,416 is. I can't seem to find any 6-digit majors showing a rank less than about 40. When we figure this out, we need to change the wording to explain the actual comparison. (Would be best to be able to get a full table of all 1,1416 courses of study, but I assume that must come in a future version).

**Comment by jspeis** [comment]
This was a mistake in the labelling. We don't have wage data at the full 6-digit CIP level. What we do is use a Census provided crosswalk to go from ACS PUMS' Field of Degree to CIP codes. However this crosswalk only has 2-digit CIP resolution. So all wage data on education pages has only 2-digit CIP resolution. So the bottom line is that the ranking for the wage stat should be out of 38 (which the number of 2 digit CIP codes). @davelandry has now fixed this, so this will be reflected in tomorrow's update.

**Comment by DannyBachman** [comment]
Good to see such quick resolution! Thanks.

**Comment by davelandry** [comment]
Cheers! :beers:
