### ISSUE TITLE
Dropping "k" abbreviations from numbers

### ISSUE THREAD

**Issue by alexandersimoes** [DataUSA/datausa-site#216]
Personally I would rather see a long number in the thousands ie 34,500 vs 34.5k on the site. I realize this is an opinion thing so wondering what some of you guys think... @pviechnicki & @danielbyler. I would still keep the M and B abbreviations for millions and billions.

**Comment by danielbyler** [comment]
I'm fine with the long number. K is a more ambiguous abbreviation than the others.
