### ISSUE TITLE
Removing use of offsetHeight

### ISSUE THREAD

**Issue by alexandersimoes** [DataUSA/datausa-site#218]
Got this warning in Chrome: 'SVGElement.offsetHeight' is deprecated and will be removed in M50, around April 2016.

I'm assuming it's coming from D3plus and that there might be a fall back anyway but just wanted to mention it.

![screen shot 2016-02-10 at 7 06 44 pm](https://cloud.githubusercontent.com/assets/252276/12966131/ac46d6e6-d029-11e5-8ba4-db4f25609038.png)

**Comment by davelandry** [comment]
Interesting, are you seeing this all over the place or was just one specific visualization? Let me know where I can replicate this.

**Comment by alexandersimoes** [comment]
if you open the console and start scrolling on any location page, think it get triggered by the first triptych
