### ISSUE TITLE
only show map tiles for the US

### ISSUE THREAD

**Issue by TroyBishop** [DataUSA/datausa-site#221]
If this is "data USA," do not render any other territory other than the United States. By showing North America, Central America and parts of South America, I want to be able to compare USA data with data from other countries. Show only territory for which you providing content.

**Comment by davelandry** [comment]
This is actually a bit trickier than just not rendering the other countries. Map tilesets are sort of geographically agnostic, and we can't just query for specific countries. It's sort of an all or nothing situation.

We could remove all of the tiles, but then you would lose all of the roads and labels for the US that are underneath the data.
