### ISSUE TITLE
location profile about bugs/improvements

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#222]
Chicago, IL profile description has "and and" in the first sentence. Also, any way to change the second sentence to read "It borders.." or even "Chicago borders", rather than "Chicago, IL borders..." ? It'd read more like a sentence.

Expand button should have "collapse" state once clicked plz 

<img width="951" alt="screenshot 2016-02-12 09 51 16" src="https://cloud.githubusercontent.com/assets/8160651/13010126/59ee879a-d16e-11e5-80e5-0a19e9748fdb.png">

**Comment by davelandry** [comment]
Todo list:
- [ ] remove "and and"
- [ ] remove name from second sentence (ie. "It borders...")
- [ ] allow collapsing of the expand button
