### ISSUE TITLE
Why are there only 2 variables available in the map for PUMS?

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#228]
This is a question, really.  How come there are only two variables available on the map view for PUMS?  I only see salary and # of people.  Are there not hundreds of variables for each observation?

-Peter

**Comment by jspeis** [comment]
These are the [base values](https://github.com/DataUSA/datausa-api/wiki/ACS-PUMS-API) we collect when aggregating from PUMS. So we have 21 fundamental base variables that we use to power the profile visualizations.

That said we also have many aggregation tables by geography, including multiple levels of detail. The [link above](https://github.com/DataUSA/datausa-api/wiki/ACS-PUMS-API) shows the complete list of possible permutations we use on the site from PUMS. There are literally millions of possible graphs we could show based on those 21 base variables PUMS (e.g. number of part-time nurses in the hospital industry by state, or average age of female dentists by PUMA etc...).

I'll let @davelandry give the definitive answer, but I think it's primarily an issue of timeline and prioritization.

**Comment by davelandry** [comment]
Here's what I was able to pull in from our API, all the stuff @jspeis linked to but also GINI:
<img width="248" alt="screen shot 2016-02-23 at 12 02 05 pm" src="https://cloud.githubusercontent.com/assets/1847581/13259593/0ac9cc68-da26-11e5-8810-7b748e77e0fe.png">
