### ISSUE TITLE
occupation profile, majors tree map legend has too many categories

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#237]
For example, in this treemap:
http://beta.datausa.io/profile/soc/291020/#education

Each major is its own legend class.  There are too many classes.  Why don't you just use stem/non-stem as the classes?

**Comment by davelandry** [comment]
I personally prefer the current coloring by parent categories. Curious what everyone else's thoughts are here.

**Comment by davelandry** [comment]
Closing this issue, as I believe the 2-digit course coloring has been accepted by the users.
