### ISSUE TITLE
remove "Imports" from input tree maps

### ISSUE THREAD

**Issue by DannyBachman** [DataUSA/datausa-site#244]
Chart under "manufacturing"

![image](https://cloud.githubusercontent.com/assets/16964476/13430168/ec67fb66-df91-11e5-9bb5-24d02267fedc.png)

Imports are not an intermediate industry and should not be included in this chart.

**Comment by davelandry** [comment]
@DannyBachman we should still Imports in the Sankey, correct?

**Comment by DannyBachman** [comment]
Yes, they should be in the Sankey, but they are a final demand component (although they show up as a subtractions, so are correctly placed on the LHS of the Sankey, and colored the same as the final demand components on the RHS. Just not included here.

Imports are often confusing in national income accounting.

**Comment by davelandry** [comment]
Got it, thanks. I'll remove them from this Tree Map on all industry profile pages.
