### ISSUE TITLE
Map share button underline misaligned

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#249]
The share modal underline under social is misaligned on open. It is fixed when toggled.

![image](https://cloud.githubusercontent.com/assets/5577360/13475349/4ca3c83a-e090-11e5-8d11-e0eb85fddafd.png)

**Comment by davelandry** [comment]
@zwhitman are you still seeing this after last Thursday's release?

**Comment by zwhitman** [comment]
nope - looks good now

**Comment by davelandry** [comment]
:beers:
