### ISSUE TITLE
remove/reduce polygon stroke from map

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#251]
The map is pretty illegible at the original extent - I think we need to lose the tract borders at anything below zoom level 10. We should probably set the county level at around zoom 5 as well.

![image](https://cloud.githubusercontent.com/assets/5577360/13475503/5affb1a4-e091-11e5-9490-2761eba699d3.png)

**Comment by davelandry** [comment]
We totally agree that the borders make things hard to see. We'll be looking at way to reduce/remove them.

What do you mean by "set the county level"?

**Comment by zwhitman** [comment]
Jumped around in that comment - i'm thinking we need to set the logic to display/not display at different zoom levels. So I'm thinking we should remove tract borders around zoom 10 and county borders around zoom 5.

**Comment by davelandry** [comment]
I don't know if it needs to be that complicated. We'll play around with it, but my feeling is that we can get the borders looking good consistently at all zoom levels.
