### ISSUE TITLE
stricter metric labels in map dropdown

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#252]
Can we add labels on all values in the map view? For example on ACS Age, we need to make sure folks know it's the median.

**Comment by davelandry** [comment]
sure, we can change "Age" to "Median Age".

I'll work with @jspeis to make sure that all of the metrics are correctly labeled. @zwhitman, do you know off-hand if any other phrasings are misleading/wrong?

**Comment by zwhitman** [comment]
Average Travel Time 
US Citizens 
smoking
Violent crime
Alcohol-impaired driving deaths
excessive drinking
homicide
Motor vehicle crash deaths

![image](https://cloud.githubusercontent.com/assets/5577360/13619680/8a28b0d6-e558-11e5-8464-93505d99e23c.png)

**Comment by davelandry** [comment]
closed with #287
