### ISSUE TITLE
Data missing from 'show data' output for degree growth

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#253]
Looking at this profile: http://beta.datausa.io/profile/cip/0403/, looking at the 'Degrees Awarded by Growth' map...

I see Allegheny County, PA listed as #3 in the text on the left.

But when I download the CSV file using 'Show Data', this county does not appear.   Either the auto-text is wrong or the data in the show data call are wrong.

**Comment by jspeis** [comment]
The text on the site was correct (if you view the JSON API call you can verify this), but there was a bug with the output formatting of the CSV that caused the line containing Allegheny County to get skipped. This should be fixed in the next update.
