### ISSUE TITLE
put an image icon next to the geo meta text

### ISSUE THREAD

**Issue by alexandersimoes** [DataUSA/datausa-site#255]
example Lycoming County, PA:

<img width="747" alt="screen shot 2016-03-04 at 3 51 56 pm" src="https://cloud.githubusercontent.com/assets/252276/13539860/0e1fffba-e221-11e5-83fa-b418596d4dab.png">

**Comment by davelandry** [comment]
Instead of adding another icon to the already busy section, I've added a text prefix instead:

<img width="1216" alt="screen shot 2016-05-31 at 2 43 55 pm" src="https://cloud.githubusercontent.com/assets/1847581/15686419/33dcd068-273e-11e6-9c1b-84a3034cd661.png">
