### ISSUE TITLE
decimal places

### ISSUE THREAD

**Issue by pabucklely** [DataUSA/datausa-site#283]
Industry tree map for US still shows two decimal places--please make it one.

**Comment by davelandry** [comment]
This will be fixed as part of tomorrow's update:<br />
<img width="1248" alt="screen shot 2016-03-16 at 11 26 01 am" src="https://cloud.githubusercontent.com/assets/1847581/13817801/f1f3a128-eb69-11e5-968e-c74484b2391a.png">
