### ISSUE TITLE
missing names on some horizontal bar charts

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#284]
The size of the numbers makes it so the names don't show up inside of the bar charts http://beta.datausa.io/profile/geo/united-states/ . I'm not sure if there is a solution to that or not. 

![image](https://cloud.githubusercontent.com/assets/3857364/13706279/7299783a-e772-11e5-9640-0d4b34a99a7d.png)

**Comment by davelandry** [comment]
I've been seeing some repercussions throughout the site as a result of taking out the thousands abbreviation (#216), specifically with axis labels.

I think it's realistic to build the functionality of having the labels format differently from values in tooltips/stats. This should hopefully address this or at least help. A guaranteed fix would be to make the charts take up a little bit more vertical space, which I think would also help readability in general.

Proposed To-Do:
* [ ] add axis specific formatting into D3plus
* [ ] increase min-height of all horizontal flexbox bar charts

**Comment by danielbyler** [comment]
Or should we revisit the thousands abbreviation? If it's causing this much work and we're close to launch, I don't mind admitting a mistake. Open to both options.

**Comment by davelandry** [comment]
I think that removing the abbreviations helps immensely when looking at specific data points. So much so that it outweighs the minimal effort to put the logic in specific for axis labels (aka "it's easy just let me do it").

That being said, if end up down a rabbit hole, we can always pull me out and revert back to abbreviations.

**Comment by danielbyler** [comment]
Sounds good
