### ISSUE TITLE
Cutoff doesn't account for scroll bar on the right

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#285]
If you go to a tooltip all the way on the right, the box will bleed so that it shows up behind the scrollbar. I couldn't get a capture of the precise event but I could get it to occur if I put my mouse in the right hand side of the farthest right bar in this chart. 
http://beta.datausa.io/profile/geo/united-states/
![image](https://cloud.githubusercontent.com/assets/3857364/13706435/162e73e2-e773-11e5-979c-85980d35005c.png)

**Comment by davelandry** [comment]
Ooooo interesting edge-case bug. I like this one.

What OS and browser were you using?

**Comment by danielbyler** [comment]
Chrome

**Comment by davelandry** [comment]
Windows 10?

**Comment by danielbyler** [comment]
Windows 8

Daniel Byler
Data Scientist (Manager)
Tel: 202-660-2969
