### ISSUE TITLE
Wording--snapshots, not trends

### ISSUE THREAD

**Issue by pabucklely** [DataUSA/datausa-site#286]
Wording on "Workforce," but may be in other sections

The current wording is "Here we present trends in jobs, wages, opportunities in the Private households Group"--these aren't trends, they are snapshots.  Suggested new wording:

"Here we present a snapshot of jobs, wages, and opportunities in the Private Households Group"

**Comment by davelandry** [comment]
Much better. This will be part of next week's update.
