### ISSUE TITLE
add units/labels to all healthcare indicators

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#287]
Is this per 100K? If so, we need to say so http://beta.datausa.io/profile/geo/united-states/

![image](https://cloud.githubusercontent.com/assets/3857364/13706534/70507604-e773-11e5-8247-69ef1873dac3.png)

**Comment by davelandry** [comment]
We should take a look at all of the health indicators we show and see what's missing labels. I think some of them are just sort of arbitrary indexes, but I know some are absolute values.

**Comment by davelandry** [comment]
For @jspeis: the indicators we need clarification on are:
* diabetes
* adult_obesity
* alcoholimpaired_driving_deaths
* excessive_drinking
* adult_smoking
* sexually_transmitted_infections
* hiv_prevalence_rate
* homicide_rate
* violent_crime
* motor_vehicle_crash_deaths

**Comment by jspeis** [comment]
The CHR API wiki page has been updated with the list of variables and descriptions:

https://github.com/DataUSA/datausa-api/wiki/County-Health-Rankings-API

**Comment by danielbyler** [comment]
Thanks!
