### ISSUE TITLE
More precise redirect

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#293]
When I click on the 'Employment Projections' link in the footer of the projections graph to get to the source, I go to bls.gov. Could we please land on the specific program page where we get the data from for all of these?

http://beta.datausa.io/profile/soc/4990XX/

**Comment by davelandry** [comment]
@jspeis if we change the link given by the API, this will come into effect automagically

**Comment by jspeis** [comment]
We should discuss this in the context of #294 since this page for our dataset is no longer directly available on the BLS site.
