### ISSUE TITLE
Average Earnings on occupaton and industry charts

### ISSUE THREAD

**Issue by pabucklely** [DataUSA/datausa-site#295]
The write-up says "Median", but the charts say "average"--they should match

**Comment by pabucklely** [comment]
Also, is it "earnings" (which might include bonuses) or "salaries"?

**Comment by davelandry** [comment]
@jspeis once you clarify which is the correct language, I can make the appropriate changes in the front-end

**Comment by jspeis** [comment]
When looking at the Nation or a State we are using PUMS data from which we compute average salary, but when looking at a place or county which are not available in PUMS -- we use the precompiled ACS estimates which have fewer occupation/industry classifications and are based around median earnings. So we should update the labels for the Nation and State pages.
