### ISSUE TITLE
Majors

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#305]
Is there ever 'major' data for when someone has 'some college' or less in the education section? http://beta.datausa.io/profile/soc/1721XX/

![image](https://cloud.githubusercontent.com/assets/3857364/13758602/9e4fe29e-ea00-11e5-8f4c-7049b99190b6.png)

**Comment by jspeis** [comment]
@davelandry is working on fixing this in the UI right now. I will just add that PUMS will never have a 'major' (field of degree) for anyone who has not attained a bachelors degree.

**Comment by davelandry** [comment]
All 3 degree dropdown menus (CIP, GEO, and SOC) are now filtered by the available degrees, thus removing the less than bachelors.
