### ISSUE TITLE
Type of degree by education

### ISSUE THREAD

**Issue by DannyBachman** [DataUSA/datausa-site#307]
Here's a curious chart for Nurse Anesthesiolgists:

![image](https://cloud.githubusercontent.com/assets/16964476/13760202/4ce339ee-ea08-11e5-9545-69e609cd0250.png)

Evidently, 10% of Nurse Anesthesiologists with doctoral degrees have those degrees in preforming and visual arts. (70 people altogether, obviously not many people, but still...). Or are these the BA degrees of those with Ph.Ds? Inquiring minds are confused (and will be confused unless we make clear what the chart is showing).

**Comment by jspeis** [comment]
The field of degree variable captured in PUMS is only contains the field of degree of the person's bachelor degree so we should add text to clarify that point.

**Comment by DannyBachman** [comment]
Great, thanks!

**Comment by davelandry** [comment]
I've added both a subtitle and more explicit paragraph text:<br />
<img width="466" alt="screen shot 2016-03-16 at 11 15 07 am" src="https://cloud.githubusercontent.com/assets/1847581/13817457/a13701a4-eb68-11e5-92d4-209c8bbdfd48.png">
