### ISSUE TITLE
Minimum cutoff for number of people in a job

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#308]
I was excited to learn that 25 people +- 45.1 are operations research analysts who work in animal slaughtering and processing. Does this violate a business rule we were trying to implement around not showing super sparse data? I forget what they all were but it just seems weird. 

http://beta.datausa.io/profile/soc/152031/

**Comment by davelandry** [comment]
Good catch, this one wasn't using the number of records cutoff for some reason.
