### ISSUE TITLE
Difference in education profiles

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#310]
What's the difference between a 6 digit code and a 2 digit code when the cover (like Math and Statistics) the exact same area? Is there any way we can better explain that?

![image](https://cloud.githubusercontent.com/assets/3857364/13760776/3ef933bc-ea0b-11e5-985f-cbeecc2244e4.png)

**Comment by davelandry** [comment]
The [wikipedia page](https://en.wikipedia.org/wiki/Classification_of_Instructional_Programs) has a pretty succinct explanation:
> Instructional programs are classified by a six-digit CIP at the most granular level and are classified according to the two-digit and four-digit prefixes of the code. For example, "Forensic Science and Technology" has the six-digit code 43.0106, which places it in "Criminal Justice and Corrections" (43.01) and "Homeland Security, Law Enforcement, Firefighting and Related Protective Services" (two-digit CIP 43).

It's just simple prefix nesting. The more digits, the deeper the nesting. When two names match (or are close), that just means it's a sort of general child category. The other classifications (like NAICS) have prettier names for the different levels ("Sectors", "Groups", etc). We wanted to stick as close to the standards that each classification have defined.
