### ISSUE TITLE
add self industry into Sankey

### ISSUE THREAD

**Issue by DannyBachman** [DataUSA/datausa-site#314]
Note the following chart, which does not include manfacturing as an input or output to itself:
![image](https://cloud.githubusercontent.com/assets/16964476/13791453/9a6fc81a-eac3-11e5-92ea-5405e0b08c2f.png)

Although the tree charts below do include it:

![image](https://cloud.githubusercontent.com/assets/16964476/13791479/bdfb7a72-eac3-11e5-84f6-aed1e35c7337.png)

I believe the tree chart is correct, and this cell is missing from the Sankey diagram.

**Comment by DannyBachman** [comment]
What is the status of this? I ask because I would really, really like to use this for a story, but I can't do it until this is fixed.

**Comment by davelandry** [comment]
I'm planning on fixing this for Thursday's update.
