### ISSUE TITLE
401 error with no option for login

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#315]
Came from IE 11.0.0600

**Comment by danielbyler** [comment]
Another identical issue from IE 11.0.9600.18205CO

**Comment by jspeis** [comment]
Which page was this on?

**Comment by danielbyler** [comment]
The login page. They can't get into the site.

**Comment by jspeis** [comment]
Can they try from another browser just to isolate if its a browser issue?

**Comment by jspeis** [comment]
Going to close this issue. Haven't seen this happen elsewhere so I'm assuming this is a particular issue with Windows/IE trying to automatically proxy credentials. Also, we won't have auth when we launch.
