### ISSUE TITLE
Messed up text in education section

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#317]
Link: http://beta.datausa.io/profile/soc/132051/

Browser: Internet explorer 11

**Comment by danielbyler** [comment]
Another person with messed up results from IE
![image](https://cloud.githubusercontent.com/assets/3857364/13848170/fbae5db2-ec26-11e5-9314-9c01c4dc1070.png)

**Comment by jspeis** [comment]
![screen shot 2016-03-17 at 10 37 22 am](https://cloud.githubusercontent.com/assets/87581/13849402/610bb042-ec2c-11e5-8dd8-61434e4cdc67.png)
