### ISSUE TITLE
more explicit majors text for a location

### ISSUE THREAD

**Issue by tschleeter** [DataUSA/datausa-site#318]
http://beta.datausa.io/profile/geo/arlington-va/#income_distro

I noticed under "Professional Doctorate" in Arlington that the only major was psychology. I think this is an error. Other cities seemed to work correctly such as San Francisco http://beta.datausa.io/profile/geo/san-francisco-ca/
I would assume that law would be #1 for Arlington too so I thought it I would bring it to your attention.

**Comment by jspeis** [comment]
@tschleeter thank you for the feedback

When I click professional doctorate on http://beta.datausa.io/profile/geo/arlington-va/#education I see 100% Clinical Psychology.

What this means, and should be clarified in the text on the site, is that 100% of Professional Doctorates awarded by Institutions in Arlington, VA were in the field of Clinical Psychology.
