### ISSUE TITLE
Homepage in IE 11/ Win 7

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#319]
![screen shot 2016-03-17 at 9 26 48 am](https://cloud.githubusercontent.com/assets/87581/13847241/9914c03c-ec22-11e5-944b-63142f19faf0.png)

**Comment by davelandry** [comment]
@jspeis I feel strongly about my fix for this one, but would you mind also checking this in Windows 7?

**Comment by jspeis** [comment]
Looks good
