### ISSUE TITLE
pixelated logo in IE 11

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#320]
![screen shot 2016-03-17 at 10 37 27 am](https://cloud.githubusercontent.com/assets/87581/13849386/500000b4-ec2c-11e5-9cd7-ec442b634573.png)

**Comment by davelandry** [comment]
@jspeis can you do a pull locally and take a look at the new image I pushed? it looks better/different to me, but I need a second set of eyes (ones that don't have a retina screen)

**Comment by jspeis** [comment]
Looks better to me! (top is new, bottom is old)

![screen shot 2016-03-22 at 3 05 25 pm](https://cloud.githubusercontent.com/assets/87581/13964332/9795a64c-f03f-11e5-809a-3d395d994b67.png)

**Comment by davelandry** [comment]
:+1:
