### ISSUE TITLE
fix labels in Native and Foreign Age visualization

### ISSUE THREAD

**Issue by tschleeter** [DataUSA/datausa-site#321]
I noticed in the native and foreign age section that the color doesn't specify which group is which. On this page: http://beta.datausa.io/profile/geo/arlington-va/#education I assume the green is native and the blue is foreign. Is that right? Also, I was looking to get percentages, when I click on a group it is only counts. Is there any way to get that statistic?

**Comment by davelandry** [comment]
I can get both percentages and the names back in there. For (my) reference, here's the link to the specific visualization (you can get that by clicking on the title of the visualization): http://beta.datausa.io/profile/geo/arlington-va/#age_nativity
