### ISSUE TITLE
mobile design for map page

### ISSUE THREAD

**Issue by zwhitman** [DataUSA/datausa-site#324]
This is probably for v2.0 but it'd be cool to see the map usable on a phone with a collapsible sidepanel.

**Comment by davelandry** [comment]
@melteng do you have any ideas on where the expand/collapse buttons should live in the current interface?

**Comment by melteng** [comment]
YES, how about top right of the side panel? You can use the same plus/minus expand/collapse buttons we have in the profiles.

Sorry, mixing issues, but I saw the collapse icon in the "About" section doesn't match the collapse icon in the profile sticky header 🙊 

<img width="168" alt="screenshot 2016-08-30 17 29 48" src="https://cloud.githubusercontent.com/assets/8160651/18107807/7bf1d552-6ed7-11e6-85be-42a94a68c36f.png">
:(

<img width="83" alt="screenshot 2016-08-30 17 29 52" src="https://cloud.githubusercontent.com/assets/8160651/18107808/7bf24708-6ed7-11e6-9476-88e98423b662.png">
:)

**Comment by davelandry** [comment]
@melteng can you make a separate issue for that collapse button?

**Comment by melteng** [comment]
yes :(

**Comment by davelandry** [comment]
Implemented in 3.0
