### ISSUE TITLE
rent vs own change text from population to homeowners

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#326]
"The largest share, 61.5%, of the population of Boston-Cambridge-Quincy, MA-NH Metro Area owns their home. This is lower than the national average of 64.4%."

Should likely be:
The largest share, 61.5%, of households in Boston-Cambridge-Quincy, MA-NH Metro Area own their home. This is lower than the national average of 64.4%.

http://beta.datausa.io/profile/geo/boston-cambridge-quincy-ma-nh-metro-area/#rent_own

**Comment by davelandry** [comment]
@jspeis can you make this change in the YAML? should just be text (no variables).
