### ISSUE TITLE
California population

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#331]
I think you're drawing CA's population from the 5 year Census. Weren't we using the 1 year estimate for large locations so it's more current?

**Comment by jspeis** [comment]
Fixed. 
![screen shot 2016-03-21 at 11 43 28 am](https://cloud.githubusercontent.com/assets/87581/13924308/2f93688a-ef5a-11e5-8df0-02bf498d2991.png)

**Comment by danielbyler** [comment]
Could you push this ahead of schedule? We're trying to do a last minute check of some numbers and can't do it if it's in staging.
