### ISSUE TITLE
add ACS source note to all applicable employment splash stats

### ISSUE THREAD

**Issue by DannyBachman** [DataUSA/datausa-site#333]
The heading for elementary and middle school teachers (occupation) lacks a note indicating that it is ACS data. BLS data is different. The growth projections show 1.99 million in 2012. I assume this is another ACS/BLS difference similar to that in the industry data. All employment figures from ACS should have their source noted.

**Comment by davelandry** [comment]
Are you referring to the 3.51M number of employees at the top of the page?

**Comment by DannyBachman** [comment]
Yes.

**Comment by jspeis** [comment]
per @melteng 's design suggestion, we have added a small note on the occupation and industry pages below the fold, next to the photo attribution information

![screen shot 2016-03-30 at 11 15 57 am](https://cloud.githubusercontent.com/assets/87581/14147314/ea90133a-f668-11e5-828a-ac4742d650ed.png)

**Comment by davelandry** [comment]
Looks great, mark this as closed?

**Comment by DannyBachman** [comment]
Not an immediate issue since we took out the BLS projections. But it's not showing up yet, is that correct?

**Comment by davelandry** [comment]
This will appear on the site after today's update.
