### ISSUE TITLE
Value on X Axis for Skills

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#334]
What is the value on the X axis for skills? http://beta.datausa.io/profile/soc/412010/ 

I tried to tie it back to the original data and the values there seem to be two values from 1-100. Did you combine the importance and the value in some way? Sorry, I'm confused but a quick label I think would fix it. 

![image](https://cloud.githubusercontent.com/assets/3857364/13967958/3abf1ce4-f050-11e5-8b02-543db37e641f.png)

**Comment by jspeis** [comment]
The value we show is the analyst rated "level" (scaleid = LV). In this example, there is no ONET data for code 41-2010. What we are doing to try to fill in these gaps, is that we aggregate data from available 4120** ONET data rows and we taking the mean level values and assign that to 412000. I can update the documentation on ONET to explain this.

Also, I noticed that it looks like ONET DB updated in February (https://www.onetcenter.org/db_releases.html). I believe we are currently using data release 20.0, but I'll need to double check.

**Comment by jspeis** [comment]
I double checked, and we are currently using version 19.0 on the site.

**Comment by danielbyler** [comment]
OK let's just note that in the about section and fix it after launch. I'm guessing it hasn't changed that much.
