### ISSUE TITLE
change h1 category tags to h2

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#338]
SEO suggestion: "Profiles: Change all h1 class=”category” tags to h2 .. Pages should only have one H1 tag"

**Comment by davelandry** [comment]
Now that the site's been out, and we're doing great in SEO, I'm going to suggest we close this issue unless there are objections.

Currently, our longest profile type (geo) has 12 H1 tags, which I think is reasonable. I'm a bit worried about making this change, as it may have some unforeseen conflicts with the CSS.
