### ISSUE TITLE
Authentication double check

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#345]
When I clicked on the terms of use, it asked me for authentication a second time. I know authentication won't be present at launch but wanted to make sure this was a glitch and not a buried call to the authentication or something like that which would mess us up at launch.

**Comment by jspeis** [comment]
We recently started load balancing requests on beta.datausa.io across multiple servers so it could be something will authentication session persistence across session that caused you to see the message twice. 

That said, the only authentication happens at the web-server level (not in our code) and that will be disabled at launch so it should not be an issue.
