### ISSUE TITLE
Wrong totals in Sankey chart

### ISSUE THREAD

**Issue by DannyBachman** [DataUSA/datausa-site#351]
The Sankey charts show the same totals for inputs and outputs of each category. I don't think the wrong numbers are being used in the charts, but I do think that incorrect numbers are reported. Notice in the chart below, manufacturing is clearly different amounts on the two sides. But if mouse over, it will give the same amount in billions.

![image](https://cloud.githubusercontent.com/assets/16964476/14189655/7358576a-f75c-11e5-8393-72ca3a2860ab.png)

**Comment by DannyBachman** [comment]
I was able to verify the figures in the tree charts with the source data. But the all the figures in the Sankey seem to be wrong. Again, I expect the chart is picking up the correct data, but it's not being reported.

While I am at it, it would really be nice to have percentages reported when you mouse over the inputs and uses in the Sankey diagram.

**Comment by davelandry** [comment]
This was an issue with the input and output values being summed up in the tooltips. Will be fixed in today's update.
