### ISSUE TITLE
update "Watertown Town, MA" name

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#354]
![img_7710](https://cloud.githubusercontent.com/assets/8160651/14285940/53c40d50-fb1b-11e5-898c-1d9c27d53989.JPG)

due diligence: name should be shortened to Watertown, MA (also called "the Town of Watertown")

**Comment by davelandry** [comment]
closing this issue, as we've decided to stay as close to the actual names as possible. It actually is technically called "Watertown Town": http://censusreporter.org/profiles/16000US2573440-watertown-town-ma/
