### ISSUE TITLE
some text overlap issues

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#355]
![img_2910](https://cloud.githubusercontent.com/assets/8160651/14287382/837519e0-fb20-11e5-8204-a9b02989a612.PNG)
![img_2909](https://cloud.githubusercontent.com/assets/8160651/14287386/8507da4a-fb20-11e5-8b08-b7a762fe4008.PNG)
![img_2911](https://cloud.githubusercontent.com/assets/8160651/14287388/87391568-fb20-11e5-82ae-7685a43235f5.PNG)

**Comment by melteng** [comment]
largely fixed by @davelandry, working on some small fixes
![img_3021](https://cloud.githubusercontent.com/assets/8160651/14798636/9cacd97a-0b06-11e6-80ce-f457063448c7.PNG)

**Comment by davelandry** [comment]
@melteng unintentionally fixes are my specialty 😎

**Comment by davelandry** [comment]
@melteng I think some of your Story styles broke the breadcrumb style for the Profiles:
<img width="305" alt="screen shot 2016-05-02 at 12 56 20 pm" src="https://cloud.githubusercontent.com/assets/1847581/14960955/5810a364-1065-11e6-91a3-a4e7a2816380.png">

**Comment by melteng** [comment]
@davelandry not sure if it's story styles, I'll look into it tom. Which type of browser is that btw?

**Comment by davelandry** [comment]
Chrome

**Comment by melteng** [comment]
![img_3150](https://cloud.githubusercontent.com/assets/8160651/15684554/9142e002-2735-11e6-9933-8f802d47be3b.PNG)

@davelandry seems to be the featured story (& other stories if the description is too long)
