### ISSUE TITLE
Options tabs non-functional in Firefox 45 on OSX Yosemite

### ISSUE THREAD

**Issue by eeeschwartz** [DataUSA/datausa-site#358]
Clicking `embed`, `download`, etc doesn't change the view of the share link.

As seen in a clean install via Browserstack:

<img width="1670" alt="screenshot 2016-04-06 11 48 01" src="https://cloud.githubusercontent.com/assets/428684/14323225/abcf66d4-fbed-11e5-813e-e480a6a7ac05.png">

Little issues aside the site's fantastic. Thanks for the great work, y'all!

**Comment by davelandry** [comment]
Thanks for the kind words and reporting this bug! We noticed this ourselves a few days ago, and are prepping a small update to address this issue. Here's the commit: https://github.com/DataUSA/datausa-site/commit/99353c041195f149180152b47ba3f00daab0b18f

**Comment by eeeschwartz** [comment]
:+1:
