### ISSUE TITLE
bottom of profiles have white bg on wide screens

### ISSUE THREAD

**Issue by alexandersimoes** [DataUSA/datausa-site#359]
![screen shot 2016-04-06 at 6 14 31 pm](https://cloud.githubusercontent.com/assets/252276/14334620/8dd04834-fc23-11e5-9283-cb453c25fa2a.png)

can be resolved by giving entire page a bg color of navy blue or removing max-width

**Comment by davelandry** [comment]
are you seeing this on the current code base? I thought I fixed that this afternoon...

**Comment by jspeis** [comment]
looks fixed on the latest version to me

**Comment by davelandry** [comment]
Even the ones I try to snipe before getting put into Github wind up in Github :smirk:

Here's the commit that closes this issue: https://github.com/DataUSA/datausa-site/commit/49246a2eeab8d283f0c739eec4803d35f5c7d4b6
