### ISSUE TITLE
add google analytics to homepage & profile links

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#370]
<img width="1211" alt="screenshot 2016-04-12 15 09 53" src="https://cloud.githubusercontent.com/assets/8160651/14472347/cc9b9cca-00c0-11e6-94ab-6f0f092c2993.png">

to measure which ui elements people actually click on (test: are we structuring the homepage in a way where people can get to the info they're looking for?), add analytics to:

Home
- red home search button
- all links to the left
- 'boxes' near top, mid, and bottom of homepage feed
- footer elements

Profile (test: how do people navigate the site?)
- all "About" section links to the sections below
- section links in the icon nav that appears when you scroll

**Comment by davelandry** [comment]
@melteng I put in tracking for all of the TOC images, along with the sub-nav links for each section.

All of the suggested home button links are already tracked. @jspeis figured out that any anchor link that goes to a new page gets tracked. There's a great google analytics plugin that can show it live, but it's also peppered throughout the analytics dashbaord ("Behavior" -> "Behavior Flow" is pretty neat)
