### ISSUE TITLE
Need to improve tool tip for Alcohol-related driving deaths

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#402]
Some of our users are getting confused by the 'Percent of Alcohol-related driving deaths' in the location profile:
<iframe width="720px" height="480px" src="http://embed.datausa.io/profile/geo/maryland/health/substance_abuse?viz=True" frameborder="0" ></iframe>
We need to make clear what the denominator is of the percent.  They don't understand it's total driving fatalities.

**Comment by davelandry** [comment]
I'm having trouble thinking of a succinct way to explicity say this, the closest I've got is: "Motor Vehicle Crash Deaths Involving Alcohol"

Here's the source documentation for this measure: http://www.countyhealthrankings.org/measure/alcohol-impaired-driving-deaths

**Comment by davelandry** [comment]
changed to "Percentage of Driving Deaths Involving Alcohol" for the next release
