### ISSUE TITLE
svg viz download

### ISSUE THREAD

**Issue by mattrdini** [DataUSA/datausa-site#403]
When downloading svg treemap visualization looses font style

**Comment by davelandry** [comment]
this is expected behavior. there's no way to embed a font into an SVG download. it will only appear correctly if you have the specified fonts on your machine.

**Comment by alexandersimoes** [comment]
Dont think it's worth reopening but a potential work around for this would be to re-render this (off screen, or even in a pop up window) using a system font before kicking off the download. This would enable text heavy viz like the tree map to text wrap this new font, whether it be the built in sans-serif or times new roman and not look broken when the user downloads it.
