### ISSUE TITLE
some universities are missing their sector

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#408]
Discovered in #406, some Universities have an administrative sector of either `null` or `99`. This causes them to have no color and icon in Tree Maps.

<img width="209" alt="screen shot 2016-06-15 at 11 06 51 am" src="https://cloud.githubusercontent.com/assets/1847581/16085858/7cd44c70-32eb-11e6-9f48-a99c7357f874.png">

**Comment by davelandry** [comment]
@jspeis can you take a look into this?

**Comment by jspeis** [comment]
@davelandry this should be fixed in ibis now. We now have sector 99 in the attribute list (99='Sector unknown (not active)' ... for the mean time I put in a dark gray placeholder color but feel free to change that). Do you have example visualizations we can test?

**Comment by davelandry** [comment]
Awesome, here's the visualization I've been using: http://datausa.io/profile/geo/illinois/education/universities/

Is that the "official" name of the sector? Seems clunky to me, like "Unknown Sector" would be better.

**Comment by jspeis** [comment]
Yep, that was the official name, changed it since "Unknown Sector" sounds much better. Looks like this on ibis now:

<img width="1065" alt="screen shot 2016-07-26 at 4 57 04 pm" src="https://cloud.githubusercontent.com/assets/87581/17155190/1b72d60e-5352-11e6-9922-5eae591026d1.png">

**Comment by davelandry** [comment]
👍  let's close it!
