### ISSUE TITLE
manual map position should persist when changing filters

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#429]
scenario: trying to find "Weston, MA", which isn't a census-designated place (apparently).

- [ ] give users the ability to close / open the side menu
- [ ] when a user has zoomed into a place and switches to another geo filter (state to msa, etc.), keep the map zoomed into that place

**Comment by davelandry** [comment]
first bullet is a duplicate of #324 

bumping the second bullet up to the main topic of this issue
