### ISSUE TITLE
pressing "enter" on profile search takes you to US profile page, not adv search

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#434]
When the top right profile search is open, it should take the user to the adv search page (with their search entry carried over). For some reason it takes you to the United States location profile.

**Comment by davelandry** [comment]
Just tested this behavior: when pressing enter in the search box after typing, the site brings you to the top result in the search (ie. "cook" will bring you to the cook county profile).

If you press enter without typing anything, nothing happens.

If you type something, then clear out, then press enter, you will be brought to the last result searched. @melteng does that describe what you were experiencing?
