### ISSUE TITLE
homepage search box weirdly magnifies the page when "down" arrow is clicked

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#435]
When you click on the search box and press the "down" arrow key, the page "freezes" (scroll disappears) but for some reason the background subtly but weirdly zooms in a little. Attaching screenshots.
![screenshot 2016-09-12 17 24 53](https://cloud.githubusercontent.com/assets/8160651/18453559/e0117e3a-790d-11e6-9f95-efc1cda636dc.png)
![screenshot 2016-09-12 17 24 58](https://cloud.githubusercontent.com/assets/8160651/18453560/e012e270-790d-11e6-8d0c-caf1a6bc66ca.png)

**Comment by alexandersimoes** [comment]
When you press down on your keyboard we turn off scrolling because we're
overriding the default browser behavior. As such the scroll bars disappear
and might be the "zoom" effect you're noticing.

**Comment by davelandry** [comment]
ahh yeah that's probably it. In macOS if you have the scrollbars always visible, they'll disappear when entering the search box, this making the background image (which is set to `cover`) slightly increase in size.

Everything still works, the background image will just sort of jump. I'm not sure there's any way around this...
