### ISSUE TITLE
handle new subs format from API

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#459]
We will need to update the logic in the frontend for handling the "subs" parameter from the API calls.

The current subs format simply shows a raw, comma separated string of what any query params were crosswalked into 

![screen shot 2016-10-13 at 1 02 04 pm](https://cloud.githubusercontent.com/assets/87581/19358791/452611a6-9145-11e6-9b10-d2d415f3d1a8.png)

The new format will only parameters show that have changed (and what they changed from/to):

![screen shot 2016-10-13 at 1 01 22 pm](https://cloud.githubusercontent.com/assets/87581/19358800/4a65b860-9145-11e6-9b30-14dc75731420.png)

**Comment by davelandry** [comment]
Deprecated with 3.0
