### ISSUE TITLE
when comparing, make maps same size?

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#460]
Any chance we could get the maps to be the same size when we're comparing profiles? I'm looking at DC vs. Boston below:

<img width="1441" alt="screenshot 2016-10-13 13 04 16" src="https://cloud.githubusercontent.com/assets/8160651/19358863/a1d18e8a-9145-11e6-89b4-fd0faacc1924.png">

**Comment by davelandry** [comment]
I'm not able to recreate this:

<img width="1260" alt="screen shot 2016-10-13 at 4 32 23 pm" src="https://cloud.githubusercontent.com/assets/1847581/19365883/c625c126-9162-11e6-8417-23851422aabf.png">

**Comment by davelandry** [comment]
Fixed in 3.0
