### ISSUE TITLE
when comparing, remove repeating "Compared to {Profile B}" title

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#461]
When you add a comparison, could we remove the righthand "Compared to Boston, MA" title that repeats every section? This would also help the actual chart title ("Most Specialized") stand out and help people reading/skimming the profiles.

To point out the names of Profile A and Profile B, two ideas could be:

1) bold the names of Profile A and B in the descriptions (ex. "Compared to the other CDPs, _Washington, DC_ has an unusually high number of ...").
2) Have a Profile A or B h4 title about the descriptions on both sides. Ex. imagine in the screenshot below the title, "In Washington, DC" above the description and below the "Most Specialized" title. On the other side in the same row, "In Boston, MA".

<img width="1402" alt="screenshot 2016-10-13 13 06 30" src="https://cloud.githubusercontent.com/assets/8160651/19358931/f2b2957e-9145-11e6-9432-ed88a9739de4.png">

**Comment by davelandry** [comment]
I like suggestion #2. In that case, would you keep the "Most Specialized" title on the right as well?

**Comment by davelandry** [comment]
Fixed in 3.0
