### ISSUE TITLE
when comparison, change color of profile B

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#462]
<img width="1442" alt="screenshot 2016-10-13 13 50 04" src="https://cloud.githubusercontent.com/assets/8160651/19360319/087be486-914c-11e6-9365-0888821169da.png">

1. the second color I used is #ff976c (a slightly lighter orange / red). In the bar charts, I also darkened the text color (it's #333) which shows up better against the colored bars. If this darker color is calculated, could we bump it up so it's easier to read? (Tangent: After using the site for a while, I think using the condensed Pathway font in the bar chart visualizations is hard to read. Maybe we can swap it out for the body font, Palanquin?)

2. I replaced the ampersand in the top nav with a bar " | " to better signify a comparison vs. a unity. I tried "v." and "vs." as well, but it didn't look good.

3. Changed the color of the same bar to white and the color of Profile B's name to #ff976c as well.

4. Removed the 3 stats bar because it was starting to look really cluttered. Do we have stats on whether this stats bar is useful to people?

5. Another idea, the [ x ] remove comparison icon should prob have a yellow outline to follow the pattern of the ( - ) circle icon. The [ ] add comparison icon could have a + inside and have a green outline.

**Comment by davelandry** [comment]
@melteng please create separate issues for:
* bar chart text color
* bar chart font family
* comparison icon color/style
