### ISSUE TITLE
On comparison pages, remove repeated/duplicate charts

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#468]
When you compare two locations, if the locations happen to be in the same state, then you get lots of repeated visualizations side-by-side.  For example, comparing Montgomery County MD with Howard County MD gives you the diabetes chart for MD 2 times.  Can we figure out a way to suppress duplicate charts on the comparison?

**Comment by davelandry** [comment]
Good catch! I've put in an exception to only duplicate the chart if the API data urls are actually different.
