### ISSUE TITLE
Legends have disappeared on comparison pages

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#469]
For example, comparing Columbus Ohio metro area with Austin Texas, all the transportation bar graphs are missing a legend:
https://datausa.io/profile/geo/columbus-oh-metro-area/?compare=austin-round-rock-san-marcos-tx-metro-area#transportation

**Comment by davelandry** [comment]
I don't believe there were ever legends on those visualizations. I believe this falls under #204
