### ISSUE TITLE
jumping to section cuts off title

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#471]
When I load http://datausa.io/profile/geo/01000US/#obesity_diabetes it seems like the page cuts off the "Obesity and Diabetes" title, I think it would be nice if we can have the title of the section appear on screen when linking

**Comment by davelandry** [comment]
That's weird. We had a solution in place for this that... just... stopped working?

Who knows when it stopped working, but I just put in a more concrete solution. Should be all set now.
