### ISSUE TITLE
home search: cap width of deep link

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#476]
for long names, the "jump to" link should have a max-width. (In general, it repeats the same thing as the search result name and can be removed, since clicking on it does the same thing as clicking on the entire result container.)

<img width="651" alt="screenshot 2016-12-07 12 12 12" src="https://cloud.githubusercontent.com/assets/8160651/21115068/95ef554a-c07d-11e6-8530-3599d8993b77.png">

**Comment by davelandry** [comment]
this looks to have been fixed? photo from the live site:

<img width="714" alt="screen shot 2017-04-13 at 12 00 31 pm" src="https://cloud.githubusercontent.com/assets/1847581/25013230/d7d9413c-2040-11e7-94a6-d9557e2073d9.png">

please let me know if this issue still persists in some places.

**Comment by melteng** [comment]
much nicer :)
