### ISSUE TITLE
Map: Option to limit Top/Bottom 10 Locations to locations with population > 500k

### ISSUE THREAD

**Issue by melteng** [DataUSA/datausa-site#480]
<img width="1439" alt="screenshot 2017-02-16 14 03 54" src="https://cloud.githubusercontent.com/assets/8160651/23036467/eead8c0e-f450-11e6-97b7-e4a6a43c327b.png">

Use case: using Data USA to help determine where a new grad might want to move (or any 20-something ;)

Of course it's interesting that Rexburg, ID is the youngest metro area, but practically I'd like to know which **major city** in the US is the youngest, has the highest median wage, lowest GINI, etc.

**Comment by davelandry** [comment]
@melteng please move your checklist of other UX notes into separate github issues.

**Comment by davelandry** [comment]
This is now achievable with the viz builder!
