### ISSUE TITLE
treemap comparison height mismatch

### ISSUE THREAD

**Issue by alexandersimoes** [DataUSA/datausa-site#512]
This bug found c/o @crisjf

![img_1858](https://cloud.githubusercontent.com/assets/252276/24724069/2ff29e08-1a20-11e7-8ed6-cfa721f7b12f.JPG)

**Comment by davelandry** [comment]
I don't believe this has to do with the tall displays, I've seen this on landscape as well. Thanks for reporting @crisjf!

**Comment by davelandry** [comment]
Fixed in 3.0
