### ISSUE TITLE
fix clinician to patient ratio comparisons for nation/non-nation

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#525]
http://sunbird.datausa.io/profile/geo/florida/?compare=united-states#health

Looking at health and safety, the visualizations don't stack side-by-side properly.
I'm looking at clinician-to-patient ratios for florida, but next to it I see insurance coverage for florida, not clinician ratios for the US.
![image](https://cloud.githubusercontent.com/assets/7073490/25241486/2d0a0924-25c4-11e7-84c7-4803a7ba5a7d.png)

### Steps to Reproduce (for bugs)

1. http://sunbird.datausa.io/profile/geo/florida/?compare=united-states#health
2. scroll to health and safety

### Your Environment

* Browser Name: Chrome
* Operating System and Version: Windows 8

**Comment by davelandry** [comment]
Deprecated in 3.0 (it's now a chart!)
