### ISSUE TITLE
merge comparison dropdown menus

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#526]
### Expected Behavior

When you choose a comparison region and set both common conditions viz to a particular condition like hospital readmittance, the second drop down gets frozen and the viz does not update.

 

When you change the condition on the left side dropdown, shouldn't the right-one update automatically so you're looking at the same comparison?

### Steps to Reproduce (for bugs)

1. http://sunbird.datausa.io/profile/geo/florida/?compare=texas#health
2. scroll to health-safety
3. select 'Hospital Readmission' under 'Common Conditions'

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
I was able to fix the dropdown for the comparison visualization, but I'm uncertain if we should make the dropdowns control both visualizations on a comparison. The reason being, sometimes the dropdowns actually have different contents. For example, the dropdowns in the Education section of an occupation only show the degree levels available for that occupation: http://sunbird.datausa.io/profile/soc/271020/?compare=291020

I suppose we could merge both dropdowns, and just have it say "no data available" if you select an option that isn't available for the comparison. I'm curious what everyone thinks. In the meantime, I'm going to reclassify this issue, as the main bug has been fixed.
