### ISSUE TITLE
Add explanatory popup or notes on health insurance viz

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#529]
Many people won't know what all the different categories of insurance mean on this visualization:
http://sunbird.datausa.io/profile/geo/phoenix-az/#health

Possible to add a note, popup, or link to the documentation telling people what all these items mean?

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Definitely doable. I'll see what I can find for definitions of each term.

**Comment by davelandry** [comment]
Newest version of the site includes pop-ups for black/non-black and definitions underneath some of the text in visualizations. If there are specific definitions that aren't on the site, we can add them as they come up now that the behavior has been coded.
