### ISSUE TITLE
Change labeling of Women's Health chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#530]
Referencing this chart:
http://sunbird.datausa.io/profile/geo/phoenix-az/?compare=new-york-ny

Let's change the labels to something like:
Racial/Ethnic Disparities in Access to Women's Preventive Care

Let's also expand the view to show all ethnicities, not just white/black.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki we don't have race data in the Dartmouth dataset for anything other than Black and White, but I like the more explicit title regardless. How about "Racial Disparities in Access to Women's Preventive Care"?
