### ISSUE TITLE
Change diabetes chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#531]
Reference:
http://sunbird.datausa.io/profile/geo/phoenix-az/#health

Can we make this chart show a rate per 1000 diabetes patients please? Right now it's not very edifying.

Also please expand to show all races.

Also please label the chart something like 'Access to Diabetes Care'

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Was able to change the title and the y-axis to a percentage share out of that race's patients. Unfortunately we only have data for black and white races 😞 

How's this look?

<img width="1148" alt="screen shot 2017-04-27 at 11 21 12 am" src="https://cloud.githubusercontent.com/assets/1847581/25490793/e8bb18a8-2b3b-11e7-9b8c-59ca587f384a.png">
