### ISSUE TITLE
Word missing in text of wages chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#532]
### Expected Behavior

"Here we can see the census tracts in Phoenix, AZ colored by Median Yearly Income for that census tract."

### Current Behavior

In the auto-text, there is a word missing:
"Here we can see the in Phoenix, AZ colored by Median Yearly Income for that ."
Actually, two words I guess.

### Steps to Reproduce (for bugs)

http://sunbird.datausa.io/profile/geo/phoenix-az/#income_geo

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki I'm unable to recreate this bug. can you check if you're still seeing it, and if so, update your original comment with your browser and OS?
