### ISSUE TITLE
Location Health & Safety Profile- Updates to Health Risks 

### ISSUE THREAD

**Issue by ecischke** [DataUSA/datausa-site#537]
Conditions and Diseases
https://datausa.io/profile/geo/jacksonville-fl  
NOTE: The link to share/embed this map is broken (the url populates with the link to the safety map instead)

Safety & Addictions
https://datausa.io/profile/geo/mesa-county-co/#crime
Recommend changing title to “Safety & Risky Behaviors”.
Need to correct paragraph text and graph legend to align with measurement rate.  Some are XX per 100,000 people and some are prevalence represented as a percentage; however all text descriptions are populating to say XX per 100,000 people.  

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Great bug catches, found the culprits and the fixes will be live with the next update.
