### ISSUE TITLE
Location Health & Safety Profile- Updates to Hospital Care Diabetes Care

### ISSUE THREAD

**Issue by ecischke** [DataUSA/datausa-site#538]
Diabetes Care
https://datausa.io/profile/geo/detroit-mi/#diabetic_care
This data should be shown as a percentage of diabetic Medicare enrollees, not number of total patients; recommend changing y-axis.  
Also, data totals in the legends are incorrect/illogical, as total displayed when you scroll over icon is greater than total # of Medicare enrollees in the county.  NOTE: treatments (eye exams, hemoglobin tests, lipid tests) are not mutually exclusive and in fact should be co-occurrences.  
Description paragraph should be corrected to indicate that data is limited to Medicare enrollees (not all patients).  NOTE: this is true for all data sourced from Dartmouth Atlas.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Great tweaks, here is an updated chart:

<img width="1338" alt="screen shot 2017-04-27 at 12 15 30 pm" src="https://cloud.githubusercontent.com/assets/1847581/25493165/41913fe6-2b43-11e7-93a2-19507abb45b9.png">
