### ISSUE TITLE
Location Profile Health & Safety - Updates to Common Conditions

### ISSUE THREAD

**Issue by ecischke** [DataUSA/datausa-site#539]
Common Conditions
https://datausa.io/profile/geo/mesa-county-co/#conditions
As a health policy subject matter expert, I cannot clearly understand what this graph is trying to depict.  The title is hospital care, does that mean that these are the most common conditions for which Medicare patients were admitted to the hospital?   Does this include both medical and surgical care?   
The paragraph text needs to be revised, but it is not clear to me what you are trying to explain with this section. 
At a minimum, the title/Subtitle should be changed to “Common Medicare Conditions”, as Dartmouth Atlas data only include Medicare patients.

The other options in the drop-down menu (readmittance within 30 days, pcp visits within 14 days, ambulatory visits with 14 days, ER visits within 30 days) do not make sense as currently represented by the bar graph or explained by the stock text.    It might make more sense to create separate graphs for each of the 3 most common conditions and then break out which of those patients had a readmittance within 30 days, PCP visit within 14 days, etc…)

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Deprecated in 3.0
