### ISSUE TITLE
insurance coverage visualization ideas

### ISSUE THREAD

**Issue by ecischke** [DataUSA/datausa-site#542]
Insurance Coverage 
https://datausa.io/profile/geo/detroit-mi/#insurance_coverage_gender

It would also be useful to visualize insurance type composition for an entire geographic area.  For example:
•	Pie chart depicting % of total with Healthcare Coverage/% of total with No Healthcare Coverage 
•	Of total with Healthcare Coverage, breakdown by type (i.e. % with public health insurance, % with private health insurance)
•	Of total with public insurance, breakdown by type (i.e. % with Medicare coverage, % with Medicaid, % with Tricare/Military, % with VA Health Care coverage); Of total with private insurance (% with employer-based, % with direct purchased)

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Deprecated in 3.0
