### ISSUE TITLE
CSV generator not working on map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#543]
Reference this map on the original site:
https://datausa.io/map/?level=state&key=income_below_poverty,income_below_poverty_moe,pop_poverty_status,pop_poverty_status_moe

### Expected Behavior

When I choose options -> download -> CSV, instead of CSV I get a json file.  

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Duplicate of #444, prioritizing fix.
