### ISSUE TITLE
Population Map Gives Impression Everyone Has Disappeared 

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#545]
https://datausa.io/map/?level=county&key=pop,pop_moe,pop_rank

The map is almost entirely white due to the skewed population. Can we color based on log(population) or something like that?

**Comment by davelandry** [comment]
The jenks color breaks should be taking care of distributing these numbers evenly, so I'll take a look and see if there's some sort of bug here.

**Comment by davelandry** [comment]
Looked into this today: the color scale breaks are functioning correctly. The problem with the population map is just that there are so many counties with very small numbers, and only a few astronomically larger ones. 

To remedy this, we added a couple more break points into the map, which seems to help.

**Comment by jspeis** [comment]
At the ACS conference last week, I heard two great talks: one by Joel Alvarez with the NYC Department of City Planning and another by David Wong. Both talks focused on pitfalls of mapping survey data. Videos of the talks should be available soon, but the slides are available [here](https://acsdatacommunity.prb.org/cfs-file/__key/widgetcontainerfiles/3fc3f82483d14ec485ef92e206116d49-s-AAAAAAAAAAAAAAAAAAAAAA-page-02017_5F00_acs_5F00_conference/Alvarez.pdf) and [here](https://acsdatacommunity.prb.org/cfs-file/__key/widgetcontainerfiles/3fc3f82483d14ec485ef92e206116d49-s-AAAAAAAAAAAAAAAAAAAAAA-page-02017_5F00_acs_5F00_conference/Wong_5F00_D.pdf).

Beyond the general reminder of the importance of reminding users of error in visualizing survey data - with regard to mapping Joel shows that as more buckets are added the reliability in terms of having distinct class buckets illustrate statistically meaningful differences goes down.

All of this is to say, I think it would probably be better to revert the changes to increase the number of buckets and perhaps consider the log approach?

**Comment by danielbyler** [comment]
I'm fine with either of those options. My personal preference is towards buckets so there is an easier and direct correspondence.

**Comment by davelandry** [comment]
Deprecated in 3.0
