### ISSUE TITLE
We've lost the 'api' link under the visualization options - please add back

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#546]
We've somehow lost the view api url option for visualizations in the 2.0 version.  E.g. this visualization:

http://sunbird.datausa.io/profile/geo/new-york-ny/#housing

Used to be you could click options and see a button labeled API and you could click and get the custom url.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki we re-organized the tab content and labels, and the API links are now located at the top of the "view data" section
