### ISSUE TITLE
overlapping labels in skills bar charts when performing occupation comparisions

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#547]
When performing a comparision between two occupations, the labels describing skills for each occupation appear to overlap.

### Expected Behavior

The labels should have a little bit more spacing

### Current Behavior

The labels overlap (see image below)

### Steps to Reproduce (for bugs)
![screen shot 2017-04-28 at 2 11 10 pm](https://cloud.githubusercontent.com/assets/87581/25541483/ce1362e4-2c1c-11e7-9218-9c88f6794fa8.png)

1. Visit an occupation page
2. Compare to another occupation
3. Visit the skills section and scroll down to the side-by-side bar charts.

Or visit: https://sunbird.datausa.io/profile/soc/291060/?compare=291020#skills

### Your Environment

* Browser Name: Chrome
* Operating System and Version:
Max OS X 10.12.4

**Comment by davelandry** [comment]
Deprecated in 3.0
