### ISSUE TITLE
maps top/bottom lists not updating after changing variables

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#551]
If you are on the maps page and switch from 2015/2016 the information toggles fine. If you go to a second or third map via the search (without reloading the page), it fails to update to the 2015 information if you toggle to 2015.

**Comment by davelandry** [comment]
We've discovered that some of the variables from CHR are actually only updated every 2 years, and in that case they just carry over the previous year's value. For example, violent crimes:
http://www.countyhealthrankings.org/app/oregon/2015/measure/factors/43/data
http://www.countyhealthrankings.org/app/oregon/2016/measure/factors/43/data

@danielbyler which variable were you seeing this behavior with? If it's a CHR variable, this is probably the issue, but if that's not the case, please list specific steps to recreate the bug you are seeing.

**Comment by danielbyler** [comment]
That's not the problem. 

1. From the home page, navigate to Maps
2. Search for Obesity and click Obesity Prevelance
3. Toggle to 2015. The top 10 stats on the left don't change. 
4. Reload the page. https://datausa.io/map/?level=county&key=adult_obesity
5. Now try the toggle. Top 2015 county is Green County, AL with 48.1% . Top 2016 county is Homes County, MS at 46.6%

**Comment by davelandry** [comment]
Ahhh ok I got it now. It's an issue with the list on the left, whenever you've changed a variable.

Thanks for the update @danielbyler! We'll get this fixed.
