### ISSUE TITLE
add a URL parameter to map page specifying zoom level and center coordinates

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#558]
The title of this enhancement request kind of says it all.  Is it possible to add parameters for zoom level and center coordinates to the map view?  For example, in this map:

https://datausa.io/map/?level=county&key=drug_poisoning_deaths

I really want to use this in a story centered on kentucky.  Would love to have a url for the map centered on kentucky and zoomed.  Recommend parameters like: zoomlevel= (integer between 1 and 10?) center_lat=latitude, center_long=longitude (decimal degrees)

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
this is a really cool idea, and I think I know just how to implement it. shouldn't be too difficult!
