### ISSUE TITLE
Bug in health visualization

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#559]
Reference: https://datausa.io/profile/geo/breathitt-county-ky/#substance_abuse

THe auto text for this chart talks about PUMAs, but the PUMA is not relevant.  Can someone check the autotext and fix it?  

"Here are the counties in Kentucky River Area Development District PUMA, KY, colored by Adult Smoking Prevalence."

This doesn't make sense because the corresponding map is showing the state, but not the PUMA.  Can we adjust the text, or add the PUMA to the map?

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
No longer an issue with the sunbird release: https://sunbird.datausa.io/profile/geo/breathitt-county-ky/#conditions_diseases
