### ISSUE TITLE
Black ambulatory

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#566]
Two issues- First, I think you're dividing by per 1,000 people not per 1,000 black people. If that's the case, I'd use the race to give it a correct denominator. 

Also, there are negative values. I know they're probably from the data but we should just truncate them to 0 as a negative value is just impossible. Same issues go for white ambulatory numbers I think

**Comment by davelandry** [comment]
@danielbyler we aren't doing any division, just reporting the number given to us from the Dartmouth Atlas.

I've created [this issue](https://github.com/DataUSA/datausa-api/issues/24) in the API repo for us to snipe all the negative values.
