### ISSUE TITLE
Ambulatory Visits

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#568]
http://sunbird.datausa.io/map/?level=county&key=patients_with_one_ambulatory_visit_to_pc_total

Can we make this per 1,000 people? LA isn't the source of all problems ;)

**Comment by danielbyler** [comment]
Same black/white comments as before for the denominator for the other two ambulatory charts

**Comment by davelandry** [comment]
@danielbyler can you elaborate on what you want to see changed here? The per 1,000 people thing is an artifact of the reported data, we aren't doing any manipulation on our end. Would you want to see this as a rate of people based on population?

**Comment by danielbyler** [comment]
Yes, that's what I'm looking for. Right now this is basically just a population map b/c it's totals and not a rate.

**Comment by davelandry** [comment]
Cool, added to the running list in #544
