### ISSUE TITLE
teen births denominator

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#569]
I think I logged this before but it's not changed. http://sunbird.datausa.io/map/?level=county&key=teen_births&translate=581.0973840590493,724.119622087442&scale=4511.930445473056

I don't think the raw data is per 1,000 people- it's per women age 15-19. That's a much more relevant denominator

**Comment by davelandry** [comment]
This variable comes from the County Health Rankings, and is per 1,000 women aged 15-19: http://www.countyhealthrankings.org/measure/learn/teen-births

I'll update the label to include the age range.
