### ISSUE TITLE
Years of life lost

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#570]
http://sunbird.datausa.io/map/?level=county&key=premature_death&translate=581.0973840590493,724.119622087442&scale=4511.930445473056

There are extremely large differences between the age adjusted and non-age adjusted numbers. Can you please work with one of the health people at Deloitte to pick the right one? My guess is age adjusted but I'm just guessing. The discrepancy is super confusing

**Comment by davelandry** [comment]
@danielbyler can you recommend someone at Deloitte for us to contact? Should we just show the age-adjusted number?

**Comment by davelandry** [comment]
Figured out that the age-adjusted measure we list is actually "Premature age-adjusted mortality"! Fixing that label now.
