### ISSUE TITLE
Need to include place names with 'view data' option on map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#571]
When the user selects 'view data' on the map, he/she should see the names of the places, not just their geoids.  

E.g. on this map, I should see county names when I choose 'view data': http://sunbird.datausa.io/map/?level=county&key=drug_overdose_deaths&translate=-288.1642054789155,4820.72643469117&scale=40812.177205666114

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
Fixed, and will be part of next update.
