### ISSUE TITLE
Uninsured label

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#574]
https://datausa.io/map/?level=county&key=uninsured - needs better label, maybe 'Percent of Population Without Health Insurance'

**Comment by davelandry** [comment]
@danielbyler we want to keep the labels somewhat concise, how do you feel about just "Percent Uninsured", which would also carry over to "Percent Uninsured (Adults)" and "Percent Uninsured (Children)"

**Comment by danielbyler** [comment]
If you want it short, I'll cave
