### ISSUE TITLE
Label for average age of full time worker

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#575]
https://datausa.io/map/?level=puma&key=avg_age_ft,avg_age_ft_moe - average full time age --- worker? I guess?

**Comment by davelandry** [comment]
I've modified the following labels:
- Average Salary (Full-Time Employees)
- Average Salary (Part-Time Employees)
- Average Age (Full-Time Employees)
- Average Age (Part-Time Employees)
- Average Work Hours (Full-Time Employees)
- Average Work Hours (Part-Time Employees)
