### ISSUE TITLE
Please scale and center map on opioid story to Kentucky

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#576]
For the opioid story, the map needs to be centered on Kentucky so the hotstpot shows up.

Thanks,
-Peter
### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
I hooked up custom scale/translate for maps on non-map pages. Let me know what you think of this zoom level and I can tweak it if necessary:

<img width="1055" alt="screen shot 2017-06-15 at 11 25 17 pm" src="https://user-images.githubusercontent.com/1847581/27210692-28e333ae-5222-11e7-88e1-5e9babd5a971.png">
