### ISSUE TITLE
Navigation not working properly on location profiles

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#577]
On the location profile, I"m only seeing the demographics section, nothing else.  Where did the health, economic, etc go?

http://sunbird.datausa.io/profile/geo/montgomery-county-md/#intro

This is a problem with the top of the page and also the left-side navigation controls.

Thanks,
-Peter
### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki should be fixed now!
