### ISSUE TITLE
Side-by-side bar chart Comparisons should use same vertical scale

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#578]
For example, when comparing insurance coverage for 2 counties, you should see the same vertical scale:

http://sunbird.datausa.io/profile/geo/montgomery-county-md/?compare=howard-county-md

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
closing as duplicate of #522
