### ISSUE TITLE
Insurance coverage chart is actually showing 'uninsured'

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#579]
http://sunbird.datausa.io/profile/geo/montgomery-county-md/?compare=howard-county-md

Title and description and scales should change to read:
'Rate of persons not covered by health insurance by age' or
'How many people in each age group have no health insurance'

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki which chart are your referencing? can you post an embed link to it?

this is the closest one I've found, but it's displaying insured population: http://sunbird.datausa.io/profile/geo/montgomery-county-md/health/insurance_coverage_gender/

**Comment by davelandry** [comment]
Deprecated in 3.0
