### ISSUE TITLE
Change title of Medicare coverage map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#580]
https://datausa.io/profile/geo/montgomery-county-md/#medicare_geo
Title should read something like:
'How many people are enrolled in Medicare, and how much money did they receive?'

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
We should try to keep some consistency with the visualization titles, which are generally more concise and are not full sentences/questions.

@pviechnicki what don't you like about the current title "Medicare Enrollment and Reimbursements by Location"?

**Comment by davelandry** [comment]
Deprecated in 3.0
