### ISSUE TITLE
Trends in Medicare reimb chart: needs legend with cpmparison and colors are not distinctive

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#581]
When you view this chart comparing two counties, eg:

https://datausa.io/profile/geo/montgomery-county-md/#medicare_time

You need a legend to tell which county goes with which line.  Also, the colors are not distinctive with the thin lines.  Need to widen lines or make color palette more distinctive.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
I've increased the thickness of the lines for all line charts, but the text legends will have to wait for #204
