### ISSUE TITLE
Don't use smoothed lines on Medicare trends chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#582]
https://datausa.io/profile/geo/baltimore-county-md/#medicare_time
Lines should be straight since we only have annual values.  Don't use splines or whatever smoothing you're using.

We also need some text to go along with this chart to give it meaning.  Something like:

"Medicare is a federal program which provides health benefits to older Americans.  Amounts of money required for reimbursements to Medicare enrollees change over time. See how per-enrollee amounts have changed in XX region as compared to national trends."

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@pviechnicki I've removed the interpolation from the line charts and added your text, along with a short sentence the includes the growth percentage.
