### ISSUE TITLE
Need consistent scale on hospital care comparison charts

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#584]
For example, comparing these two counties, you need consistent scales:
http://sunbird.datausa.io/profile/geo/baltimore-county-md/?compare=montgomery-county-md

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
duplicate of #522
