### ISSUE TITLE
Add: 'Medicare' to titles of all visualizations derived from Dartmouth atlas

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#586]
Eg: https://datausa.io/profile/geo/baltimore-county-md/#womens_health
This chart should say something like, 'Rates of Preventive Women's Health Services for Medicare Patients'

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
I would prefer to keep the titles succinct, and let the sub-titles and description texts make the distinction, especially now with the larger section being titled "Hospital Care for Medicare Patients".

**Comment by davelandry** [comment]
Deprecated in 3.0
