### ISSUE TITLE
Need to improve auto-text for health conditions map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#587]
https://datausa.io/profile/geo/baltimore-county-md/#conditions_diseases
This map should have more robust text, saying something like:
'Which counties in [STATE] have the highest rates of [CONDITION]?  This map shows how counties compare according to numbers of people suffering from XX.  Baltimore County has the highest rate of XX per thousand, and its rate increased in 20XX by XX to YY%."

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
<img width="475" alt="screen shot 2017-06-14 at 6 15 10 pm" src="https://user-images.githubusercontent.com/1847581/27157014-a212bd9e-512d-11e7-8de9-f553cb7b6467.png">
