### ISSUE TITLE
Need to improve auto text and title for risky behaviors chart

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#588]
Need better title for this chart:
https://datausa.io/profile/geo/baltimore-county-md/#risky
Something like: 'Risky/Harmful Behaviors'
'Which counties in STATE have the highest rates of behaviors which can be hazardous to your health?  Baltimore County shows the highest rate of BEHAVIOR with XX per thousand.  This behavior increased in 20XX by YY% from the previous year."

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
see #587 for example of new text
