### ISSUE TITLE
Change name of map topic to "Medicare Costs and Coverage"

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#590]
In the maps pane, need to change the topic label at top left to reflect that we're talking only about medicare:
http://sunbird.datausa.io/map/?level=county&key=home_health_reimbursements_b

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
There are 3 variables in that list that are not Medicare only (they come from the County Health Rankings):
* [Percent Uninsured](http://sunbird.datausa.io/map/?level=county&key=uninsured)
* Percent Uninsured (Adults)
* Percent Uninsured (Children)

Unless we find a better place to put those, I think that the title of "Health Care Costs and Coverage" works best, especially given that most of the Medicare variable explicitly say "Medicare" in their titles.

**Comment by davelandry** [comment]
Deprecated in 3.0
