### ISSUE TITLE
Update picture for Fairfax, VA (place)

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#596]
THe current picture for the Fairfax VA profile (https://datausa.io/profile/geo/fairfax-va/) shows the Washington Monument.  Can we change it to something more local?

Something from this list?

http://www.fairfaxva.gov/government/historic-resources/historic-buildings-and-sites

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by vbebo** [comment]
![Screen Shot 2019-07-30 at 2 52 45 PM](https://user-images.githubusercontent.com/42971299/62156829-c5f00680-b2d9-11e9-987a-30295120d1af.png)

suggested site link brought me to that, so I will check Flickr

**Comment by vbebo** [comment]
poked around that site but the images were so small. it was surprisingly difficult to find something in Fairfax (not the county). Added to the spreadsheet B]
