### ISSUE TITLE
compared university shows duplicated map

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#645]
[In this comparison](https://university.datausa.io/profile/university/massachusetts-institute-of-technology/?compare=stanford-university)
<img width="1338" alt="screen shot 2018-01-15 at 10 57 42 am" src="https://user-images.githubusercontent.com/87581/34951078-0fe167d6-f9e3-11e7-9c76-9b97c7709d64.png">

the map on the lower right should show Stanford's map in California, but right now it looks like it duplicates MIT's MA map.

**Comment by davelandry** [comment]
turns out this bug isn't just for universities, but location pages as well 😢
