### ISSUE TITLE
500 error when visiting the Ivy Tech Community College profile

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#664]
Putting this here as a reminder: I noticed that there's a 500 error when visiting the Ivy Tech Community College profile.

**Comment by davelandry** [comment]
@jspeis thanks, I'll take care of it

**Comment by davelandry** [comment]
fixed with this commit: https://github.com/DataUSA/datausa-site/commit/dae5b6762ef6ef6c12dc4a27d31ecd81e06f60b6
