### ISSUE TITLE
add clarification for Carnegie profiles

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#665]
For the University profiles representing the Carnegie classes, it would be nice to add a note that lets users know that the values represent the median value for the class.

**Comment by davelandry** [comment]
@jspeis what were you thinking, something at the top of the page in the about section? subtitle for the entire profile?

**Comment by davelandry** [comment]
Added the following disclaimer in the About section:

> ALL STATISTICS ARE CALCULATED AS MEDIANS OF THE UNDERLYING UNIVERSITY VALUES.

**Comment by jspeis** [comment]
The only thing that might be confusing looking at this again is that there are 7 occurrences where the profile says total e.g. "Doctoral Universities has a total enrollment of 15,323" would we be able to just to substitute the word median for the carnegie groups? (or remove the word total?)

**Comment by davelandry** [comment]
@jspeis good catch, I'm also adding a couple more grammar catches (ie. "have" instead of "has)
