### ISSUE TITLE
piecemeal CMS

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#677]
- [x] make each element handle it's own display vars
- [x] make each element take an ID and retrieve it's own data from a single endpoint
  - [x] profile
    - [x] subtitles
    - [x] descriptions
    - [x] generators
    - [x] materializers
    - [x] stats
    - [x] visualizations
  - [x] section
    - [x] descriptions
  - [x] topic
    - [x] subtitles
    - [x] descriptions
    - [x] stats
    - [x] visualizations
- [x] move variable getter out to tree and populate it via hash table

**Comment by jhmullen** [comment]
Finished via c7cd707453a28c9d775735544f8a03098c0c14f9 and c25cab2363b075f6ebdc97c39d41b6199707918f , closing
