### ISSUE TITLE
Text of Major first page

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#69]
Please clearly indicate that this is for under-graduate majors.

**Comment by davelandry** [comment]
Can you elaborate on this? What do you mean by "Major first page"?

Maybe through in a screenshot of a copy/paste of the specific text you want to change.

**Comment by danielbyler** [comment]
This is the same as the other pages I was looking at in my string of comments. Basically, there was nothing on the page to tell me that this page was focusing on people with undergraduate degrees as opposed to masters or PhD in math or statistics (or who knows just maybe that as a personal skill with no education). That was my concern. Does that make more sense?

**Comment by davelandry** [comment]
Unless specifically stated, the education data presented on all pages includes all degree types. @danielbyler, if there's a specific spot you can pinpoint that is unclear, we can re-open this issue.

**Comment by danielbyler** [comment]
Sorry, let me clarify. When you find whether people are high school educated, etc. in the demographics section, your response makes sense. I mainly mean when people pick 'Computer Science' in the 'Education' section, they might think they're seeing results for Computers Science assocaites, bachelors, masters, and PhD's all pooled together. Does that make sense?

**Comment by davelandry** [comment]
@danielbyler when viewing an education profile (ie. http://beta.datausa.io/profile/cip/1107/), unless it is explicitly stated in the visualization (ie. http://beta.datausa.io/profile/cip/1107/#grads_ethnicity_gender), all of the data you are seeing is for all degree types pooled together. There is no distinction between associates, bachelors, etc.

If you are not talking about the education profiles as a whole, I am still unclear as to where we are showing only undergraduate data and not stating as such.
