### ISSUE TITLE
implement story builder in CMS

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#691]
This should be a new tab in the CMS (current interface would be called "Profilew"). Stories should be treated very similarly to Profiles, but they're a little less complicated.

Here's a checklist of features/structure:

* [x] add tab interface to admin panel ("Profiles" and "Stories" would be the initial 2 tabs)
* story
  * [x] title (one-line text input)
  * [x] slug (one-line text input) :trollface: 
  * [x] image (one-line text input)
  * [x] description(s)
  * [x] author(s)
    * [x] name (one-line text input)
    * [x] title (one-line text input)
    * [x] image (one-line text input)
    * [x] twitter (one-line text input)
    * [x] bio (quill editor)
  * [x] footnote(s) - would work similar to "dumb materialized generators", in that we should be able to add new footnotes that would have the following properties:
    * id - auto-incrementing from 1 (not user-defined), and would be a way for us place links within text (ie. maybe user types `Foot{{2}}` and it runs a formatter to turn that into an anchor link that goes to the footer of the page). This could be something we might want to bring to profile down the road, so let's come up with a solution that doesn't conflict with our existing language.
    * description (quill editor, only 1 per footnote)
  * [x] topic(s) - should have all the properties of a Profile topic:
    * [x] title
    * [x] slug
    * [x] type
    * [x] subtitle(s)
    * [x] stat(s)
    * [x] description(s)
    * [x] visualization(s)

**Comment by davelandry** [comment]
example of a story on the current site: https://datausa.io/story/06-12-2017_medicare-physicians/

**Comment by jhmullen** [comment]
moving dev on this to the `canon-stories` branch as to not break the prod mortar db.

**Comment by jhmullen** [comment]
This is rough around the edges design-wise, but functional.  We can discuss the process for merging `canon-stories` back to `master` at a time that's convenient to you.

**Comment by davelandry** [comment]
@jhmullen now that you've got this working, go ahead and make the appropriate tables in the main production database, and then submit a PR (for my review) merging `canon-stories` to `canon`

**Comment by davelandry** [comment]
I'm also re-opening this, as the PR itself should be the thing that closes this issue.

**Comment by jhmullen** [comment]
Closing this as its been merged into `canon`
