### ISSUE TITLE
fix "Preview as" dropdown

### ISSUE THREAD

**Issue by jhmullen** [DataUSA/datausa-site#704]
Preview-as drop down refers to all levels (profile, section, topic). The current behavior is that you can only select a preview by opening the top-level profile and setting it, however any entity needs to be able to change this and have it propagate entirely through the profile tree.

- [x] Convert preview selector to reusable Module
- [x] Add callback behavior that sets the "current preview" as a top-level variable so any new clicks can use it
- [x] Add behavior that switches the preview id when a new profile (or its subheads) are opened

**Comment by jhmullen** [comment]
@davelandry Right now the Preview IDs are hardcoded into each editor (profile, section, and topic) and it is naively the same across all profiles (geo, cip, for now)

**Comment by jhmullen** [comment]
@davelandry I have componentized this into Preview.jsx and added appropriate callbacks.  Please add new tickmarks to this issue for any other enhancements you'd like (such as the automatic pruning of the dropdown based on profile click)

**Comment by davelandry** [comment]
@jhmullen for now, closing this issue. any changes/additions will be new issues
