### ISSUE TITLE
Refactor Move Buttons into Cards themselves

### ISSUE THREAD

**Issue by jhmullen** [DataUSA/datausa-site#705]
Currently the MoveButton component lives next to each card (generatorCard, textCard, visualizationCard, selectorCard) in a div.

Similar to footerbuttons, the Movebuttons should be INSIDE the cards themselves - such that they know how to move themselves around with their siblings, and we need not repeat movebuttons at the top level profile/section/topic editors

**Comment by davelandry** [comment]
@jhmullen how about a little settings cog menu like with the tree?

**Comment by jhmullen** [comment]
@davelandry agreed on a cog setting. I'm making a note of that in the new issue since moving to `canon`.
