### ISSUE TITLE
decrease profile secondary color opacity

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#72]
Could you decrease the opacity of the national average so it's clear which time series is primary?

![image](https://cloud.githubusercontent.com/assets/3857364/11719826/7a7c1872-9f2a-11e5-9e48-12d7b805e8d8.png)

**Comment by davelandry** [comment]
@melteng, I think the best solution here might be to just lighten the secondary color for all of the visualizations. Would probably help out the scatter plots in the health section as well.

Thoughts?
