### ISSUE TITLE
Canon: Drug Deaths Don't Add Up

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#724]
![image](https://user-images.githubusercontent.com/3857364/44733790-54e71400-aab6-11e8-81d6-ddc03d6a5195.png)

(drug deaths nationally)

Vs

(drug deaths at the state level)

![image](https://user-images.githubusercontent.com/3857364/44733838-721be280-aab6-11e8-872c-a9a4673e2485.png)

The additive bar chart in the bottom left gives the false impression in the state view that there are many more people dying than when you select the national view. I believe this is b/c you are just adding up things that are actually rates. For any graph which is a rate, this isn't an appropriate chart (but the line chart is just fine). Can we have a dictionary and suppress this kind of chart for all rate related charts?

**Comment by danielbyler** [comment]
And this is the line chart that is OK

![image](https://user-images.githubusercontent.com/3857364/44734077-100fad00-aab7-11e8-8b9f-44d91865ccc4.png)

**Comment by danielbyler** [comment]
In general, I am confused why we have both this stacked line chart and the stacked bar chart (feels like we should pick one) but as long as we have both, they are both incorrect. This has to be fixed before we can launch because adding rates is simply incorrect. 

![image](https://user-images.githubusercontent.com/3857364/47033800-b9803000-d143-11e8-8fcb-f5fea3c90071.png)

**Comment by davelandry** [comment]
@danielbyler agree 100%. This will be fixed before launch.

**Comment by davelandry** [comment]
confirmed fixed in `lassen`
