### ISSUE TITLE
unable to change "allowed" in CMS

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#730]

**Comment by davelandry** [comment]
@jhmullen I'm bubbling this up to your TODO for next week, it appears that we can't change the Allowed status anywhere! (I've tried doing profile stats and topics)

for now, I have been going into the db manually to change them

**Comment by davelandry** [comment]
@jhmullen ...this done?

**Comment by jhmullen** [comment]
@davelandry Yes sorry, closing.
