### ISSUE TITLE
income by location visualization doesn't load on county pages

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#737]
### Expected Behavior

Income by Location on county pages doesnt seem to load

### Current Behavior

Visualization does not load

### Steps to Reproduce (for bugs)

1. https://canon.datausa.io/profile/geo/05000US25017#income_geo

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

**Comment by davelandry** [comment]
Fixed on `joshua-tree`, was an issue where we weren't loading the correct topojson for Tracts and Places because those files are split out by state.
