### ISSUE TITLE
Gini on non PUMS geographic level profiles should indicate when substitution is made

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#738]
### Expected Behavior

When viewing an MSA profile for example, the text in the economy section should indicate that the wage gini value is coming from PUMS and a geographic substitution may have occurred.

### Current Behavior

The current profiles (other than nation/state/puma) will show the GINI value on the page but don't indicate that a geographic substitution was made.

### Steps to Reproduce (for bugs)

1. e.g. Detroit MSA page (31000US19820)

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

**Comment by davelandry** [comment]
fixed on `ulysses`
