### ISSUE TITLE
language for visualizations from IPEDS completions source

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#739]
### Expected Behavior

The completions data source measures the number of degrees awarded.

### Current Behavior

Currently, the measures are labelled as "XYZ graduates" though technically might be more correct to say "XYZ degrees awarded".

### Steps to Reproduce (for bugs)

1. See https://canon.datausa.io/profile/geo/04000US25#education
2. also https://canon.datausa.io/profile/university/166683#graduates

**Comment by davelandry** [comment]
Just finished a huge pass on `ulysses` to fix this language across geography, university, and CIP profiles.
