### ISSUE TITLE
Jefferson County, GA county profile fails to load

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#741]
### Expected Behavior

The Jefferson County, GA would load (or at least, partially load with available data)

### Current Behavior

Accessing the page directly returns:

```
"error": "TypeError: Cannot read property 'join' of undefined",
"stackTrace": "TypeError: Cannot read property 'join' of undefined\n    at Object.eval (<anonymous>:7:103)\n    at module.exports.__webpack_exports__.a (/home/deploy/datausa-site/static/assets/server.js:167376:338)\n    at Viz.render (/home/deploy/datausa-site/static/assets/server.js:21942:92)\n    at ...
```

### Steps to Reproduce (for bugs)

1. Visit geo profile 05000US13163

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS

**Comment by davelandry** [comment]
Fixed, confirmed working on `joshua-tree`
