### ISSUE TITLE
PUMA profiles show N/A for name and display incorrect stats

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#743]
### Expected Behavior

To see profile name and matching population numbers

### Current Behavior

N/A for profile name and possible state values for some stats (like population...no puma has over a million people)

<img width="699" alt="screen shot 2018-10-11 at 4 12 24 pm" src="https://user-images.githubusercontent.com/87581/46831135-9125b980-cd70-11e8-80b2-a9d017f7d8ac.png">

### Steps to Reproduce (for bugs)

1. visit a puma profile eg `/profile/geo/79500US2500506`

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS

**Comment by jspeis** [comment]
also, looks like the population numbers are an issue with county pages as well (looks like counties show state values)

**Comment by davelandry** [comment]
Fixed both the PUMA profiles and County populations in `joshua-tree`
