### ISSUE TITLE
some text in university profile is hard coded to Northeastern?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#745]
### Expected Behavior

it will vary based on university selected

### Current Behavior

<img width="404" alt="screen shot 2018-10-11 at 4 36 11 pm" src="https://user-images.githubusercontent.com/87581/46832384-e0b9b480-cd73-11e8-9de8-6db7e7990916.png">

### Steps to Reproduce (for bugs)

1. `/profile/university/163286`

**Comment by davelandry** [comment]
Good catch @jspeis. Fixed in `joshua-tree`
