### ISSUE TITLE
employment by occupations treemap not displaying

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#747]
### Expected Behavior

to see a treemap of occupations in (or nearby) the given location

### Current Behavior

no treemap appears? Let me or @hwchen know if there are any issues with data/API.

### Steps to Reproduce (for bugs)

1. `/profile/geo/16000US3651000#tmap_occ_num_emp`

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS

**Comment by davelandry** [comment]
@jspeis I've fixed this to show the current Treemap we have hooked up, which uses PUMS.

In the old Data USA, we use raw ACS here, but I can't find that data (number of employees by occupation) in the new cubes. Do we have this data or should we just default to using PUMS for everthing?

**Comment by jspeis** [comment]
@hwchen I think we should have this data in ACS, right? And if so which cube would this be?

**Comment by davelandry** [comment]
closing in favor of #788
