### ISSUE TITLE
geomaps on place profiles not loading?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#748]
### Expected Behavior

see pin drop in state map like previous datausa

### Current Behavior

Map doesn't load

<img width="423" alt="screen shot 2018-10-11 at 5 09 36 pm" src="https://user-images.githubusercontent.com/87581/46834210-c3d3b000-cd78-11e8-99e4-98c6f1f12a1a.png">

### Steps to Reproduce (for bugs)

1. visit place profile e.g. `/profile/geo/16000US2483775`

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS

**Comment by davelandry** [comment]
Fixed maps on `joshua-tree`
