### ISSUE TITLE
substitutions in about text on product profile

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#749]
### Expected Behavior

If the data in the about paragraph is based off the SCTG codes instead of NAPCS (FAF is SCTG), we would just wanted to note that product codes were substituted in this paragraph similar to how it happens in the vizs below:

<img width="460" alt="screen shot 2018-10-12 at 12 27 09 pm" src="https://user-images.githubusercontent.com/87581/46881664-334dac00-ce1a-11e8-8228-0947b79932c8.png">

### Current Behavior

Data presented appears to reflect the original NAPCS product,

<img width="413" alt="screen shot 2018-10-12 at 12 24 18 pm" src="https://user-images.githubusercontent.com/87581/46881595-fed9f000-ce19-11e8-9c93-37ecc85cb0c9.png">

### Steps to Reproduce (for bugs)

1. `/profile/napcs/342`

**Comment by davelandry** [comment]
Good call, added that in `joshua-tree`
