### ISSUE TITLE
Canon: bad default Geomap zoom (mercator)

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#751]
For opioid death rates counties, the zoom on the map is the whole world. It should be centered on the US

![image](https://user-images.githubusercontent.com/3857364/47033912-f8ae8100-d143-11e8-846d-e4fa0b41f352.png)

**Comment by danielbyler** [comment]
Bonus: lack of zoom controls make the chart not usable.

**Comment by davelandry** [comment]
We've fixed the default zoom, but we still need to add in the zoom controls (when enlarged)

**Comment by davelandry** [comment]
Closing this issue in favor of this issue directly in vizbuilder: https://github.com/Datawheel/canon/issues/169
