### ISSUE TITLE
Canon: x-axis final year cropped off

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#753]
While in Chrome, the year cuts off in the axis of the line chart

![image](https://user-images.githubusercontent.com/3857364/47034229-c2253600-d144-11e8-877a-252b488cf292.png)

**Comment by danielbyler** [comment]
https://canon.datausa.io/visualize?groups=0-Z2dHlfO&measure=txWmY

**Comment by davelandry** [comment]
Confirmed fixed in `joshua-tree`
