### ISSUE TITLE
Canon: Data Quality Question

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#754]
As far as I can tell, every single state in this data set has the same value year over year. I find that tough to really believe. Is that really the case?
![image](https://user-images.githubusercontent.com/3857364/47034418-5099b780-d145-11e8-946b-0814d80b3588.png)

**Comment by jspeis** [comment]
@danielbyler it appears the 2014 & 2015 compilations of the County Health Rankings both use the same 2006-2012 source years for this measure (see [source CHR](http://www.countyhealthrankings.org/app/oregon/2015/measure/factors/87/data). The measure appears to not be available after 2015). 

That said, we'll make sure users can see that. The data should come through but right now it appears as "undefined" in the tooltip. 

<img width="568" alt="screen shot 2018-10-16 at 5 11 14 pm" src="https://user-images.githubusercontent.com/87581/47047985-1a6d2f80-d167-11e8-8bc9-2cbb1de4f3eb.png">

@davelandry @hwchen there does seem to be an issue though with displaying the stat source and underlying years. I'll make a separate issue for that.
