### ISSUE TITLE
underlying data source and data years not showing for CHR variables

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#755]
### Expected Behavior

When viewing the tooltip of CHR visualizations, see the underlying datasets and years

### Current Behavior

<img width="568" alt="screen shot 2018-10-16 at 5 11 14 pm" src="https://user-images.githubusercontent.com/87581/47048099-6a4bf680-d167-11e8-9015-b620dd7d2b0b.png">

### Steps to Reproduce (for bugs)

1. https://canon.datausa.io/visualize?groups=0-z7J78&measure=Z1hS30j
2. Hover over a state

**Comment by davelandry** [comment]
Closed in favor of https://github.com/Datawheel/canon/issues/293
