### ISSUE TITLE
avoid adding SAT scores in vizbuilder

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#756]
### Expected Behavior

Display SAT scores in the standard scale from 200 - 800

### Current Behavior

SAT scores get summed in stacked area

### Steps to Reproduce (for bugs)

1. `/visualize?groups=0-1W4bia&measure=Z1uA3zw`

<img width="623" alt="screen shot 2018-10-17 at 8 29 43 am" src="https://user-images.githubusercontent.com/87581/47086401-5a73f700-d1e7-11e8-9119-35f96aac61c9.png">

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS

**Comment by davelandry** [comment]
Closing in favor of: https://github.com/Datawheel/canon/issues/444
