### ISSUE TITLE
some health sections have blank items in dropdowns on geo profile

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#757]
### Expected Behavior

see labels of available variables in dropdowns

### Current Behavior

There are some blank options under "social needs" and "behavioral health conditions" 

<img width="450" alt="screen shot 2018-10-17 at 12 43 56 pm" src="https://user-images.githubusercontent.com/87581/47102334-73da6a80-d20a-11e8-9b21-f86c445acd66.png">
<img width="452" alt="screen shot 2018-10-17 at 12 42 15 pm" src="https://user-images.githubusercontent.com/87581/47102421-b8fe9c80-d20a-11e8-80ed-9d8cd785bea4.png">

(appears to be the same on both fossil-lake and canon so I don't think its related to the recent changes on fossil-lake but perhaps might have been caused from previous renames or schema cleanup?)

### Steps to Reproduce (for bugs)

1. e.g. /profile/geo/16000US3651000#behavior
2. or /profile/geo/16000US3651000#social_needs

**Comment by davelandry** [comment]
Thanks, I think this is totally a CMS thing. Us not you :-)

**Comment by davelandry** [comment]
Confirmed working on `joshua-tree`
