### ISSUE TITLE
visualization rendering issues with certain bar charts

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#762]
### Expected Behavior

Usually, visualizations render correctly, but randomly sometimes it seems I've noticed bar charts that will render strangely.

### Current Behavior

Most of the times, charts work as expected but I've noticed that once in a while (maybe 2/100 profile views) a particular viz may have a single bar that gets misdrawn and the text gets drawn outside the bar and the bar is drawn shorter than it ought to be

<img width="1104" alt="screen shot 2018-10-19 at 9 01 29 am" src="https://user-images.githubusercontent.com/87581/47219837-f59ed500-d37d-11e8-9019-049cd4f5033e.png">

### Steps to Reproduce (for bugs)

Unable to reproduce this. Though I've seen it happen in both Firefox & Chrome.

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS 10.13.6

**Comment by davelandry** [comment]
I believe this has to do with the user's mouse triggering a mouse event of one of the shapes while it is animating in, which halts all animation. We already catch for this, but obviously something is leaking through. Moved this to `d3plus-viz`: https://github.com/d3plus/d3plus-viz/issues/107
