### ISSUE TITLE
weird position of the tooltips

### ISSUE THREAD

**Issue by cnavarreteliz** [DataUSA/datausa-site#763]
![image](https://user-images.githubusercontent.com/5233593/47510201-0653bd00-d84e-11e8-8ade-25e583749e0a.png)

### Expected Behavior

The position of the Tooltips should be above titles

### Current Behavior
The position of the Tooltips are below titles

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name: Google Chrome
* Operating System and Version: MacOS Mojave

**Comment by davelandry** [comment]
fixed on `theodore`
