### ISSUE TITLE
freight data vizs should show which FAF region is being used if crosswalk occurs

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#767]
### Expected Behavior

When crosswalking geos for FAF data, user should be notified if the results aren't representative of the current profile page

### Current Behavior

Going to a city like Cambridge, MA which isn't a state or FAF region doesn't tell users data is getting substituted.

### Steps to Reproduce (for bugs)

1. visit `/profile/geo/cambridge-ma#trade_growth`

**Comment by davelandry** [comment]
Updated subtitle and paragraph text on `ulysses`
