### ISSUE TITLE
Error message doesn't make sense

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#768]
https://joshua-tree.datausa.io/visualize?groups=0-Zpn26u&measure=2sUCF4

Press 'delete' under the group by and I get 

![image](https://user-images.githubusercontent.com/3857364/49227950-4b708f00-f3b8-11e8-9e91-9abb5aec75e7.png)

**Comment by davelandry** [comment]
Good catch, that button shouldn't even be there for the first grouping option (users always need at least 1 grouping).

Removing it in the core vizbuilder code, issue moved to here: https://github.com/Datawheel/canon/issues/322
