### ISSUE TITLE
Loss of typed value

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#769]
On https://joshua-tree.datausa.io/visualize?groups=0-Zpn26u&measure=2sUCF4 

if I specify my value first (in this case 3)

![image](https://user-images.githubusercontent.com/3857364/49228311-144ead80-f3b9-11e8-8d36-854931f64881.png)

but then select my indicator, it loses my 3 and reloads 0- not an ideal user experience. It should keep the 3 as the value. 

![image](https://user-images.githubusercontent.com/3857364/49228386-3ba57a80-f3b9-11e8-8661-2716dc943471.png)

**Comment by davelandry** [comment]
Another good catch, moving this issue to the core vizbuilder codebase: https://github.com/Datawheel/canon/issues/323
