### ISSUE TITLE
Source is missing

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#770]
https://joshua-tree.datausa.io/visualize?groups=0-z7J78&measure=19cq1W

![image](https://user-images.githubusercontent.com/3857364/49228537-9212b900-f3b9-11e8-9469-911ed2758852.png)

**Comment by davelandry** [comment]
Fixed in the latest release: https://katahdin.datausa.io/visualize?groups=0-z7J78&measure=19cq1W
