### ISSUE TITLE
Network Error when changing filter value

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#775]
Changing the filter value from 5 to .1 results in a network error

![image](https://user-images.githubusercontent.com/3857364/49238172-dc9e3080-f3cd-11e8-8dd4-197389f3ac8c.png)

**Comment by davelandry** [comment]
I'm unable to reproduce this on `katahdin`, can you confirm if this is still happening for you?

Looking into this, I also found this formatting bug: https://github.com/Datawheel/canon/issues/325

**Comment by danielbyler** [comment]
Yep, still happening

**Comment by davelandry** [comment]
@danielbyler what browser in OS are you using?

**Comment by davelandry** [comment]
@danielbyler also, if you could write out the steps you do to get this error. I'm able to load `0.1` just fine and `5` returns no data: https://katahdin.datausa.io/visualize?filters=0-Z1SQGYF-5-0.1&groups=0-z7J78&measure=Z2ny7rj

**Comment by danielbyler** [comment]
Chrome. It's if you load 5 first and then .1. Try entering a bunch of numbers in a row. That may be what does it.

**Comment by davelandry** [comment]
fixed in `niagara`
