### ISSUE TITLE
cache all first-level vizbuilder permutations

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#777]
Visualizations, especially filters, can take it feels like half a second to load. Have you load tested this?

**Comment by davelandry** [comment]
@danielbyler which visualizations are you referring to? the vizbuilder ones with filters or the profile ones with dropdowns?

**Comment by danielbyler** [comment]
Vizbuilder

**Comment by davelandry** [comment]
We're planning on caching all of the default data calls (every measure in the main list), but a 0.5 second load time for more advanced filters does sound reasonable, as there are so many permutations possible with the cube architecture that it's somewhat expected that some will have to query the DB cold without a cache.

@jspeis does this sound about right to you?

**Comment by danielbyler** [comment]
My concern isn't .5 seconds for a single user. My concern is if there are 10 concurrent users does it stack and become a full 5 second queue. Does that make sense?

**Comment by davelandry** [comment]
Ahhh I see what you mean. Theoretically it would take half a second for the first user, but at that point that result would be cached and spread across the CDN (Cloudflare) so that subsequent users are delivered a file cached on a network node close to them. Is that correct @jspeis?

**Comment by davelandry** [comment]
@jspeis has implemented a script to cache all of the first-level permutations
