### ISSUE TITLE
income by location not showing tracts for places

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#782]
### Expected Behavior

Would expect to see a tract map inside the place

### Current Behavior

Shows a map of nearby places

### Steps to Reproduce (for bugs)

1. e.g. `/profile/geo/cambridge-ma#income_geo`
2. or `/profile/geo/new-york-ny#income_geo`

**Comment by cnavarreteliz** [comment]
It's working in Olympic [https://olympic.datausa.io/profile/geo/cambridge-ma#income_geo](https://olympic.datausa.io/profile/geo/cambridge-ma#income_geo)

**Comment by jspeis** [comment]
almost there @cnavarreteliz  -- we just need to fix the text on the left to list the top tracts instead of the top places <img width="1156" alt="screen shot 2019-01-07 at 8 58 15 pm" src="https://user-images.githubusercontent.com/87581/50805151-10b71c00-12bf-11e9-8606-32a67580e74c.png">

**Comment by davelandry** [comment]
logiclayer updated on pinnacles: https://pinnacles.datausa.io/api/data?Geography=16000US0455000:tracts&drilldowns=Race&measure=Household%20Income%20by%20Race&year=all
