### ISSUE TITLE
GEO profile audit

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#783]
- [x] fix N/As in nation profile
- [x] fix chart labelRotations (`xConfig: {labelRotation: false}`)
- [x] modify API for Nation similar geographies to show some states (@davelandry)
- [x] incomplete/broken topojson for Place level (maybe it's a problem with Geomap)

**Comment by cnavarreteliz** [comment]
@davelandry can you check the similar states for Nation level? [https://olympic.datausa.io/profile/geo/united-states#income](https://olympic.datausa.io/profile/geo/united-states#income)

I was thinking in an endpoint like:
`/api/data?Geography=01000US,01000US:similarStates&measure=Household Income by Race`

**Comment by davelandry** [comment]
good point @cnavarreteliz, I'll make `similar` return some comparator states.

**Comment by davelandry** [comment]
@cnavarreteliz the `:similar` relation now returns top/bottom states for the United States, and I've fixed the viz/text in the income section: https://pinnacles.datausa.io/profile/geo/united-states/economy/income/
