### ISSUE TITLE
carnegie group link text hard to read?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#784]
It might just be me and my Flux settings and/or the specific combination of the MIT image, but do other people find it hard to read the "Doctoral Universities" link on the University profile?

<img width="892" alt="screen shot 2018-12-06 at 7 30 47 pm" src="https://user-images.githubusercontent.com/87581/49620137-b0664f00-f98d-11e8-9d44-225a308185b8.png">

**Comment by davelandry** [comment]
Ahhh that makes sense, those ones (and not the "STEM Field" subtitles) are actual links to the Carnegie profiles, so this must be inheriting the blueprint "blue" links.
