### ISSUE TITLE
instructors by academic rank and gender says no data

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#785]
### Expected Behavior

to see the viz for Instructors by Academic Rank and Gender

### Current Behavior

no data shows up
<img width="1270" alt="screen shot 2018-12-06 at 7 35 05 pm" src="https://user-images.githubusercontent.com/87581/49620260-1d79e480-f98e-11e8-97a6-c166e5ee456a.png">

### Steps to Reproduce (for bugs)

1. try `/profile/university/163286#instructors_sex`

**Comment by cnavarreteliz** [comment]
Fixed in `lassen` using `Total Instructional Employees` instead `Median Total Instructional Employees`

**Comment by davelandry** [comment]
@cnavarreteliz can you confirm that this also got ported to `mammoth`, the current CMS server?
