### ISSUE TITLE
only Nation/State/PUMA should use PUMS for industry/occupation vizs

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#788]
### Expected Behavior

Vizzes related to industry/occupation counts for MSA/places should use ACS instead of PUMS because the PUMS data won't actually cover the same geography. (Nation/State/PUMA levels however can use PUMS)

https://datausa.io/profile/geo/new-york-ny/#tmap_occ_num_emp
https://datausa.io/profile/geo/new-york-ny/#tmap_ind_num_emp

### Current Behavior

The industry and occupation data appears to come from PUMS instead of ACS 

### Steps to Reproduce (for bugs)

1. `/profile/geo/new-york-northern-new-jersey-long-island-ny-nj-pa-metro-area/`
2. or `/profile/geo/new-york-ny`

**Comment by davelandry** [comment]
For myself for later: https://saguaro.datausa.io/api/data?Geography=16000US3651000&measure=Workforce%20by%20Occupation%20and%20Gender,Workforce%20by%20Occupation%20and%20Gender%20Moe&year=latest&drilldowns=Occupation&parents=true

**Comment by davelandry** [comment]
Dependent on https://github.com/Datawheel/datausa-tracker/issues/230

**Comment by jspeis** [comment]
just to note: counties should also use the ACS data as well (as is the case on current data usa)

**Comment by davelandry** [comment]
@jspeis so... another way to look at it would be: Nation and States be the only levels using PUMS? Is that correct?

**Comment by jspeis** [comment]
Plus PUMA, so only Nation/State/PUMA would use PUMS

**Comment by davelandry** [comment]
@jspeis this has not been addressed on `xenium`. The change effected not only those 2 tree maps, but also the "top/bottom" bar charts underneath each, as well as the text accompanying each viz.

**Comment by jspeis** [comment]
I took a look at the new york page and it seems like the data might be coming from the wrong cube for the 'Highest Paid' section for occupations? If it's not using gender I think that viz should be using  the `acs_ygo_occupation_for_median_earnings_1` cube?

https://xenium-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJBQ1MgT2NjdXBhdGlvbiIsIkFDUyBPY2N1cGF0aW9uIiwiT2NjdXBhdGlvbiJdXSwiY3V0cyI6W1tbIjE2MDAwVVMzNjUxMDAwIl0sWyJHZW9ncmFwaHkiLCJQbGFjZSIsIlBsYWNlIl1dLFtbMjAxN10sWyJZZWFyIiwiWWVhciIsIlllYXIiXV1dLCJjdWJlIjoiYWNzX3lnb19vY2N1cGF0aW9uX2Zvcl9tZWRpYW5fZWFybmluZ3NfMSIsIm1lYXN1cmVzIjpbIk1lZGlhbiBFYXJuaW5ncyBieSBPY2N1cGF0aW9uIl19

**Comment by davelandry** [comment]
@jspeis good catch, I've updated `xenium`. Is it correct that "Median Earnings by Occupation" is the only one with a rollup table? I'm using the "by Gender" tables for the number of employees, RCA, and all of the Industry charts.
