### ISSUE TITLE
Convert to Rate

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#79]
http://beta.datausa.io/profile/geo/04000US42/

You are plotting absolute values here while the chart above shows the rate. We need to do rates both to be consistent and because otherwise most states will look this chart with the county with the state's major city in the top right and everything else being squished (and honestly being more of a population chart than a disease chart). 

Also, for both this and the prior chart the legend needs to say what the rate is per (infections per 100,000 people, etc.). I think this makes sense for the X/Y axis because then the chart will show well as an embed. 

![image](https://cloud.githubusercontent.com/assets/3857364/11746287/67a284e0-9feb-11e5-83d9-a136304178ad.png)

**Comment by danielbyler** [comment]
Same deal on telling me what the rate is for the crime and safety chart. I need to know the denominator (per XX people) to interpret the chart.

**Comment by davelandry** [comment]
I think the solution here is just a better description of these measures, as they aren't calculated by us and I know they have some weird limitations. @jspeis, do you have any additional knowledge on this?

**Comment by davelandry** [comment]
closed in favor of #26
