### ISSUE TITLE
behavioral health conditions vizs not loading

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#790]
### Steps to Reproduce (for bugs)

Visit `/profile/geo/05000US06037#behavior`. I tried changing to "Adults with Serious Mental Illness" also didn't load -- but changing to "Opiod Overdose Death Rate" does load.

### Your Environment

* Browser Name: Chrome
* Operating System and Version: OS X

**Comment by davelandry** [comment]
good catch @jspeis, this was caused by a regression in the logiclayer logic to find the "year" dimension to use for things like "year=latest". It had switched to using "Start Year" instead of "End Year", which was causing viz logic to break because it was expecting "End Year"
