### ISSUE TITLE
use fiscal year for treemap on spending

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#792]
When we show a treemap of spending for the US government by year, we should likely use the "Fiscal Year" dimension (instead of the calendar year dimension)

<img width="1862" alt="screen shot 2018-12-19 at 9 48 00 am" src="https://user-images.githubusercontent.com/87581/50227245-51cca800-0373-11e9-9eec-690135632010.png">

When we show a line chart of data by year and month it's clear what periods are covered, so using the action date calendar is ok. But when we summarize for a year, the federal fiscal year is different than the calendar year (i.e. fed fiscal year ends in September) , and most totals should likely follow the FY year totals.

 Does the above visualization use the fiscal year? If not, can we change that and have the text reflect that we're referring to "fiscal year" of 2017?

[see here for Fed fiscal year info](https://en.wikipedia.org/wiki/Fiscal_year#Federal_government)

**Comment by davelandry** [comment]
thanks @jspeis, I think we had hard-coded that to 2017 because of an earlier bug in the logiclayer, but I'll do some testing and let you know.

**Comment by davelandry** [comment]
Confirmed Treemap is using Fiscal Year, and clarified text on `voyageurs`
