### ISSUE TITLE
enrollment by race and ethnicity viz

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#793]
### Expected Behavior

Would expect the viz to render as something like
<img width="936" alt="screen shot 2019-01-07 at 9 06 44 pm" src="https://user-images.githubusercontent.com/87581/50805396-28db6b00-12c0-11e9-8075-8320598b3d39.png">

### Current Behavior

<img width="1904" alt="screen shot 2019-01-07 at 9 07 01 pm" src="https://user-images.githubusercontent.com/87581/50805407-427cb280-12c0-11e9-92da-35875181d326.png">

### Steps to Reproduce (for bugs)

1. visit `/profile/university/yale-university#enrollment_race`

### Your Environment

* Browser Name: Chrome (and also Firefox)
* Operating System and Version: macOS 10.13

**Comment by cnavarreteliz** [comment]
@davelandry the problem is related with the builder, because we cannot sorting the visualizations (there are two left-arrows)
![image](https://user-images.githubusercontent.com/5233593/50849139-df892b00-1354-11e9-90df-9e15c78a02c8.png)

**Comment by davelandry** [comment]
good catch @cnavarreteliz, this was a weird edge-case error where both visualizations had an order value of `1`. I've made the change directly in the DB, cleared the site cache, and all looks good now!
