### ISSUE TITLE
list of geo hierarchies inside of "about section" is too long

### ISSUE THREAD

**Issue by cnavarreteliz** [DataUSA/datausa-site#795]
### Expected Behavior

![image](https://user-images.githubusercontent.com/5233593/51180324-f07ef280-18a6-11e9-9976-f16baf8c3552.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/5233593/51180337-f83e9700-18a6-11e9-82b4-dbfd026885a9.png)

### Steps to Reproduce (for bugs)

1. `/profile/geo/16000US3651000`
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
this was fixed in `olympic`, but the changes just percolated to `pinnacles` this morning:

<img width="1238" alt="screen shot 2019-01-15 at 10 56 41 am" src="https://user-images.githubusercontent.com/1847581/51192312-49a15300-18b4-11e9-877b-679fc6f53864.png">
