### ISSUE TITLE
N/As on certain Industry Profiles

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#796]
https://pinnacles.datausa.io/profile/naics/81393

**Comment by cnavarreteliz** [comment]
@hwchen @davelandry we haven't data for `Labor unions` category: https://quincy-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJCTFMgSW5kdXN0cnkgRmxhdCIsIkJMUyBJbmR1c3RyeSBGbGF0IiwiSW5kdXN0cnkiXV0sImN1dHMiOltbWyI4MTM5MyIsIjgxMzkzMCJdLFsiQkxTIEluZHVzdHJ5IEZsYXQiLCJCTFMgSW5kdXN0cnkgRmxhdCIsIkluZHVzdHJ5Il1dXSwiY3ViZSI6ImJsc19ncm93dGhfaW5kdXN0cnkiLCJtZWFzdXJlcyI6WyJJbmR1c3RyeSBKb2JzIFRob3VzYW5kcyAyMDA2Il19

I revised old-DataUSA and that section has data: [https://datausa.io/profile/naics/81393/](https://datausa.io/profile/naics/81393/)

**Comment by davelandry** [comment]
@jspeis @hwchen any idea why this data would be missing in the new database?

**Comment by cnavarreteliz** [comment]
@hwchen do you have the logs for any of those profiles? thanks! and @davelandry I know that in old versions you fixed an issue related with the profile's render even if there was a bug in the code.

**Comment by cnavarreteliz** [comment]
also, we have problems with `bls_growth_occupation`.

[https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJCTFMgT2NjdXBhdGlvbiBGbGF0IiwiQkxTIE9jY3VwYXRpb24gRmxhdCIsIk9jY3VwYXRpb24iXV0sImN1dHMiOltbWzE1MTI1MV0sWyJCTFMgT2NjdXBhdGlvbiBGbGF0IiwiQkxTIE9jY3VwYXRpb24gRmxhdCIsIk9jY3VwYXRpb24iXV1dLCJjdWJlIjoiYmxzX2dyb3d0aF9vY2N1cGF0aW9uIiwibWVhc3VyZXMiOlsiT2NjdXBhdGlvbiBFbXBsb3ltZW50IFRob3VzYW5kcyAyMDE2IiwiT2NjdXBhdGlvbiBFbXBsb3ltZW50IFRob3VzYW5kcyAyMDI2Il19](https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJCTFMgT2NjdXBhdGlvbiBGbGF0IiwiQkxTIE9jY3VwYXRpb24gRmxhdCIsIk9jY3VwYXRpb24iXV0sImN1dHMiOltbWzE1MTI1MV0sWyJCTFMgT2NjdXBhdGlvbiBGbGF0IiwiQkxTIE9jY3VwYXRpb24gRmxhdCIsIk9jY3VwYXRpb24iXV1dLCJjdWJlIjoiYmxzX2dyb3d0aF9vY2N1cGF0aW9uIiwibWVhc3VyZXMiOlsiT2NjdXBhdGlvbiBFbXBsb3ltZW50IFRob3VzYW5kcyAyMDE2IiwiT2NjdXBhdGlvbiBFbXBsb3ltZW50IFRob3VzYW5kcyAyMDI2Il19)

**Comment by davelandry** [comment]
Closing in favor of: https://github.com/Datawheel/datausa-tracker/issues/219
