### ISSUE TITLE
N/A's for Number of Employees on place pages

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#798]
<img width="634" alt="screen shot 2019-01-25 at 11 25 30 am" src="https://user-images.githubusercontent.com/87581/51758604-128d2780-2094-11e9-8ea6-dc15c9521ff9.png">

See `/profile/geo/lowell-ma/`

**Comment by cnavarreteliz** [comment]
@jspeis I just checked and we haven't data from Lowell, MA (`16000US2537000`)

[https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJQbGFjZSIsIlBsYWNlIl1dLCJjdXRzIjpbW1siMTYwMDBVUzI1MzcwMDAiXSxbIkdlb2dyYXBoeSIsIlBsYWNlIiwiUGxhY2UiXV1dLCJjdWJlIjoiYWNzX3lnc2lfZ2VuZGVyX2J5X2luZHVzdHJ5XzEiLCJtZWFzdXJlcyI6WyJXb3JrZm9yY2UgYnkgSW5kdXN0cnkgYW5kIEdlbmRlciJdfQ==](https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJQbGFjZSIsIlBsYWNlIl1dLCJjdXRzIjpbW1siMTYwMDBVUzI1MzcwMDAiXSxbIkdlb2dyYXBoeSIsIlBsYWNlIiwiUGxhY2UiXV1dLCJjdWJlIjoiYWNzX3lnc2lfZ2VuZGVyX2J5X2luZHVzdHJ5XzEiLCJtZWFzdXJlcyI6WyJXb3JrZm9yY2UgYnkgSW5kdXN0cnkgYW5kIEdlbmRlciJdfQ==)

**Comment by cnavarreteliz** [comment]
Should we have data for Lowell, MA?

Meanwhile, I'm hiding N/A values from stats.

![image](https://user-images.githubusercontent.com/5233593/52012684-ffc28a80-24b9-11e9-9cd7-13838d2e0f65.png)

**Comment by jspeis** [comment]
I would want to confirm with Walther but there does seem to be a similar cube with the data? 

https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJZZWFyIiwiWWVhciIsIlllYXIiXV0sImN1dHMiOltbWyIxNjAwMFVTMjUzNzAwMCJdLFsiR2VvZ3JhcGh5IiwiUGxhY2UiLCJQbGFjZSJdXV0sImN1YmUiOiJhY3NfeWdzaV9nZW5kZXJfYnlfaW5kdXN0cnlfY18xIiwibWVhc3VyZXMiOlsiV29ya2ZvcmNlIGJ5IEluZHVzdHJ5IGFuZCBHZW5kZXIiXX0=

Usually "c" cubes are "collapsed" versions of the tables meaning that they will have fewer options for the kinds of industries/occupations but when using it anyways to aggregate for a place I would think this would be ok? (assuming the totals for the C cube match the totals for the other cube in other places, like New York for example)

**Comment by cnavarreteliz** [comment]
@jspeis @hwchen @davelandry Investigating more deeply I found the bug.

Logiclayer returns data from `acs_ygsi_gender_by_industry_1 ` and it should return data from `acs_ygsi_gender_by_industry_5`.

[https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJZZWFyIiwiWWVhciIsIlllYXIiXV0sImN1dHMiOltbWyIxNjAwMFVTMDYwNjMwOCJdLFsiR2VvZ3JhcGh5IiwiUGxhY2UiLCJQbGFjZSJdXV0sImN1YmUiOiJhY3NfeWdzaV9nZW5kZXJfYnlfaW5kdXN0cnlfY181IiwibWVhc3VyZXMiOlsiV29ya2ZvcmNlIGJ5IEluZHVzdHJ5IGFuZCBHZW5kZXIiXX0=](https://redwood-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJZZWFyIiwiWWVhciIsIlllYXIiXV0sImN1dHMiOltbWyIxNjAwMFVTMDYwNjMwOCJdLFsiR2VvZ3JhcGh5IiwiUGxhY2UiLCJQbGFjZSJdXV0sImN1YmUiOiJhY3NfeWdzaV9nZW5kZXJfYnlfaW5kdXN0cnlfY181IiwibWVhc3VyZXMiOlsiV29ya2ZvcmNlIGJ5IEluZHVzdHJ5IGFuZCBHZW5kZXIiXX0=)

**Comment by cnavarreteliz** [comment]
@davelandry [https://redwood.datausa.io/api/data?Geography=16000US0606308&measure=Workforce%20by%20Industry%20and%20Gender,Workforce%20by%20Industry%20and%20Gender%20Moe](https://redwood.datausa.io/api/data?Geography=16000US0606308&measure=Workforce%20by%20Industry%20and%20Gender,Workforce%20by%20Industry%20and%20Gender%20Moe)

**Comment by davelandry** [comment]
Found the problem and pushed a fix, will updated redwood later today.
