### ISSUE TITLE
N/A's for university stats?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#800]
It looks like on the live DataUSA we also don't have data on acceptance rates for University of Phoenix, so that one is ok to be N/A but we should have enrollment numbers?

`/profile/university/university-of-phoenix-arizona/`

vs

`https://datausa.io/profile/university/university-of-phoenix-arizona`

**Comment by cnavarreteliz** [comment]
solved in quincy
![image](https://user-images.githubusercontent.com/5233593/51769718-7f1f1b00-20c2-11e9-9982-043cc87b72dd.png)
