### ISSUE TITLE
hardcoded text in SOC profiles

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#807]
<img width="1076" alt="screen shot 2019-02-12 at 4 47 35 pm" src="https://user-images.githubusercontent.com/87581/52670229-0273a580-2ee6-11e9-8b62-115fe7af4d55.png">

e.g. see `/profile/soc/291131/#locations`

**Comment by jspeis** [comment]
also appears to be hardcoded in the Race & Ethnicity section as well

**Comment by davelandry** [comment]
fixes on `ulysses`
