### ISSUE TITLE
duplicated visualizations in viz builder?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#808]
Not sure if there is an easy way to prevent this given, all the combinations that we have to deal with, but just wanted to note that when trying `/visualize?groups=0-BNDBG&groups=1-1WnF7j-DOC&measure=1g4zN3` the first three vizs appear to be duplicated with the same information

<img width="1545" alt="screen shot 2019-02-13 at 10 44 27 am" src="https://user-images.githubusercontent.com/87581/52724074-a9a31c00-2f7c-11e9-8b8d-e1f3be370e94.png">

**Comment by davelandry** [comment]
moved to https://github.com/Datawheel/canon/issues/434
