### ISSUE TITLE
Missing Bars/Vars in geo profile

### ISSUE THREAD

**Issue by jhmullen** [DataUSA/datausa-site#812]
In the Housing Section of Geo, under the "Household Income" and "Property Value" sections, the bar charts are missing data for the selected town (in this case, battery park), and only has bars for USA:

https://theodore.datausa.io/profile/geo/battery-park-city-greenwich-village-&-soho-puma-ny#category_income

There is also an N/A stat, and the x-axis needs some readability attention.

**Comment by davelandry** [comment]
Missing data in cube. Moved to here: https://github.com/Datawheel/datausa-tracker/issues/229
