### ISSUE TITLE
NAPCS profile page errors

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#826]
`/profile/napcs/14101`

Also

* 14102
* 14201
* 14301
* 14401
* 14501

(Note sure if it is relevant in this case, but keep in mind that not all NAPCS codes have SCTG equivalents)

**Comment by davelandry** [comment]
This was caused because there is actually no data available at all for those NAPCS codes. I've added some front-end catches, and put in a small disclaimer message for the (already sparse) NAPCS profiles on `voyageurs`
