### ISSUE TITLE
clarify substitution in health vizs

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#827]
`/profile/geo/cambridge-ma#clinician_patient_ratio`

The subtitle says the data is available at the state level but the paragraph references "**Primary care physicians in Cambridge, MA** see an average of 954 patients per year. This represents a 0.421% increase from the previous year (950 patients)." So that should be Massachusetts?

Also seems to be the case in the `health_spending` and `conditions_diseases`

**Comment by davelandry** [comment]
Fixed on `voyageurs`
