### ISSUE TITLE
cip profile uses ygb rca instead of ycb rca?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#828]
the results for the specialized places in the CIP profile looked off to me and it looks like the `/profile/cip/computer-science-6#global_diversity` section might be using a YGB RCA instead of a YCB RCA?

<img width="1909" alt="screen shot 2019-02-25 at 9 40 00 am" src="https://user-images.githubusercontent.com/87581/53344779-84e66700-38e1-11e9-89a4-d004c730a036.png">

**Comment by davelandry** [comment]
Fixed on `voyageurs`
