### ISSUE TITLE
norway hard coded in CIP profile

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#832]
<img width="1152" alt="screen shot 2019-02-27 at 7 20 37 pm" src="https://user-images.githubusercontent.com/87581/53532434-e31f6f80-3ac4-11e9-9776-5e69b7fc13c0.png">

`/profile/cip/mechanical-engineering-6#global_diversity`

**Comment by davelandry** [comment]
Fixed in `voyageurs`
