### ISSUE TITLE
rca in global diversity on CIP should filter low record counts

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#833]
for computer science antigua & barbuda comes up in the specialized list, though it likely has only 1 or 2 records collapsed and would likely be filtered if applying the current Data USA's record count >= 5 filter.

see `/profile/cip/computer-science-6`

and

<img width="1529" alt="screen shot 2019-02-27 at 7 25 03 pm" src="https://user-images.githubusercontent.com/87581/53532590-6f319700-3ac5-11e9-9cd1-0c896eefabfd.png">

**Comment by davelandry** [comment]
@jspeis I just completed a large PUMS audit on `voyageurs`, and fixed dozens of stats and visualizations across the CIP, SOC, and NAICS profiles that were not filtering by record count (and a few incorrect RCA measures thrown in). Thanks for bringing this to my attention.
