### ISSUE TITLE
N/A's in non english speakers sections

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#834]
on Idaho geo page for example:

<img width="997" alt="screen shot 2019-03-01 at 9 13 51 am" src="https://user-images.githubusercontent.com/87581/53643558-61356080-3c02-11e9-9a62-91778ccdbc67.png">

**Comment by davelandry** [comment]
@jspeis looked into this. We're actually missing data in the DB: https://github.com/Datawheel/datausa-tracker/issues/237
