### ISSUE TITLE
Suppress names of Census tracts

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#84]
http://beta.datausa.io/profile/geo/16000US4159000/

I would guess that 10,000 people or less know the number of the Census tract they live in. The listing of the 'top sub-locations' works just great when you label top counties within a bigger region, etc. However, could we just suppress the top 'Census Tracts' when we collapse down to that level. I just don't think it's meaningful text to almost anyone since the good chart to the right is already color coded. If this is hard to implement, let's raise to the broader group but I figure you can add logic to the text for this case. 

![image](https://cloud.githubusercontent.com/assets/3857364/11747488/7c3d0618-9ff1-11e5-9b2d-d5fd3d60f876.png)

**Comment by davelandry** [comment]
wait, you don't know about Portland's census tract 046.02!?

good idea, we'll look at removing the top stats when they are census tracts :smirk:

**Comment by danielbyler** [comment]
Thanks!
