### ISSUE TITLE
election data mockups

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#852]

**Comment by gabrielaperezponce** [comment]
@davelandry Here I am placing the latest progress of these proposals 

Version 1: Map and selectors

![datausa-electoral-data-spv2- 01](https://user-images.githubusercontent.com/5561308/63551601-96f93900-c503-11e9-935a-5b28247b7e1f.png)
![datausa-electoral-data-spv2-02](https://user-images.githubusercontent.com/5561308/63551602-96f93900-c503-11e9-92a3-28171b30ebe9.png)
![datausa-electoral-data-spv2-03](https://user-images.githubusercontent.com/5561308/63551603-96f93900-c503-11e9-876f-53523ae6de89.png)

Version 2: Selectors and bars/circles (U.S.House)

![datausa-electoral-data-spv2-04](https://user-images.githubusercontent.com/5561308/63551604-96f93900-c503-11e9-9e62-714c4d1c3f09.png)
![datausa-electoral-data-spv2-05](https://user-images.githubusercontent.com/5561308/63551605-9791cf80-c503-11e9-9cfe-4bd41831773c.png)
![datausa-electoral-data-spv2-06](https://user-images.githubusercontent.com/5561308/63551606-9791cf80-c503-11e9-8e05-d1002823335a.png)

**Comment by gabrielaperezponce** [comment]
ok, should I then work on a new simpler splash or in this section of data within the profile? @davelandry

**Comment by gabrielaperezponce** [comment]
@davelandry here is an idea about this:


![mockups-electoral-datausa_01](https://user-images.githubusercontent.com/5561308/63896963-b2f85100-c9c1-11e9-9b27-8958a98f4946.png)
![mockups-electoral-datausa-02](https://user-images.githubusercontent.com/5561308/63896964-b2f85100-c9c1-11e9-8377-51d4a4f83833.png)

**Comment by davelandry** [comment]
great work @gabrielaperezponce!

Please do 1 more splash mockup that's even more simple:
- the original 6 stats centered as they are on the current site
- add 1 new row of stats underneath with only 2 stats: "Governor" and "Senator"
- underneath each name, write "Democrat" with a small blue circle next to the text

**Comment by gabrielaperezponce** [comment]
Hi @davelandry   
I was working on these ideas today, but I think maybe I am deviating a lot from what can really be done in the cms. Do you have suggestions on how to address this? 
![county-datausa-electoraldata 01](https://user-images.githubusercontent.com/5561308/64210159-871d1580-ce70-11e9-9ac4-b5a47c67de3b.png)
![county-datausa-electoraldata-02](https://user-images.githubusercontent.com/5561308/64210160-87b5ac00-ce70-11e9-867d-9051d320db34.png)

**Comment by davelandry** [comment]
@gabrielaperezponce these are great, but don't get too fancy with the maps! For these "Essex County, MA" pages, just should a "normal" map of Massachusetts! (similar to the map of California from your first mockups)

take a look at the "add comparison" feature, which makes the splash have even LESS space for information.

**Comment by jspeis** [comment]
Just to check on one thing: @Jayrmajithia @walambrecht do we have available data on governors too for all states?

**Comment by Jayrmajithia** [comment]
As of right now, we don't have any data about the governors for all states.

**Comment by gabrielaperezponce** [comment]
trying to clean and order this @davelandry 

![electoral-sp-datausa-03](https://user-images.githubusercontent.com/5561308/64307538-633afc00-cf64-11e9-978d-ac9888d4d67c.png)
![electoral-sp-datausa-04](https://user-images.githubusercontent.com/5561308/64307539-633afc00-cf64-11e9-8b12-4467702d3d11.png)
![electoral-sp-datausa-05](https://user-images.githubusercontent.com/5561308/64307540-633afc00-cf64-11e9-86ba-282213b7eb13.png)
![electoral-sp-datausa-06](https://user-images.githubusercontent.com/5561308/64307541-63d39280-cf64-11e9-88c8-347a0d8a72ff.png)

**Comment by gabrielaperezponce** [comment]
Hi @davelandry , I worked on some ideas for organizing/distribution information, I also tried to test how this translates to mobile format.

**Ideas**
![datausa-electoraldata-sp-07](https://user-images.githubusercontent.com/5561308/65001956-10e4ce00-d8c8-11e9-950e-180b40624e70.png)
![datausa-electoraldata-sp-08](https://user-images.githubusercontent.com/5561308/65001957-10e4ce00-d8c8-11e9-81c7-a5398be36fe4.png)
![datausa-electoraldata-sp-09](https://user-images.githubusercontent.com/5561308/65001958-10e4ce00-d8c8-11e9-9ea6-e42289046646.png)
![datausa-electoraldata-sp-10](https://user-images.githubusercontent.com/5561308/65001959-117d6480-d8c8-11e9-9497-64e4ff81ed05.png)

**Testing**
![ma-datausa-electoraldata-11](https://user-images.githubusercontent.com/5561308/65001501-0f1a0b00-d8c6-11e9-8cb6-8ffaa4dd403e.png)
![ma-datausa-electoraldata-12](https://user-images.githubusercontent.com/5561308/65001502-0f1a0b00-d8c6-11e9-94b5-e9dc0e2f9425.png)
![ma-datausa-electoraldata-13](https://user-images.githubusercontent.com/5561308/65001503-0f1a0b00-d8c6-11e9-8e90-86c241d0fd8d.png)
![ma-datausa-electoraldata-14](https://user-images.githubusercontent.com/5561308/65001505-0fb2a180-d8c6-11e9-989f-fca5fa12da6a.png)

**Mobile**
![mob-electoraldata](https://user-images.githubusercontent.com/5561308/65001782-4e952700-d8c7-11e9-9c78-beeaedff0411.png)
