### ISSUE TITLE
train on finding data using the viz builder

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#853]
@vbebo I'm going to put together a short little list of some common questions we get asked of Data USA (ie. "where do hairdressers make money?") and the idea is to go from that question to the _best_ representation we have using the viz builder (all in an effort to get people to use what we have instead of jumping to another site).

**Comment by vbebo** [comment]
Hi Dave,

Thanks for using Github and for reaching out to me.
While we do not have that data on our site, it may be available directly from the raw Census: https://censusreporter.org

Best,

-Victor-

**Comment by vbebo** [comment]
JK bring it on

**Comment by davelandry** [comment]
@vbebo find the best vizbuilder URLs for the following 5 fake user questions. Don't get too hung up on trying to find the best answer (some of these are tricky or we can't answer them directly), but it's more important to educate the users on what we DO have:
 - "how many women ride their bike to work in Florida?"
 - "what percentage of citizens do not have access to running water?"
 - "how has the chlamydia rate been increasing?"
 - "what are the most common jobs held by american samoans?"
 - "how much does the military spend on oil?"

**Comment by davelandry** [comment]
👏 that's exactly right

**Comment by vbebo** [comment]
0.14% of citizens do not have access to Complete Plumbing
https://datausa.io/visualize?enlarged=c-lineplot-AUJuc-Z1VhpXp-1&groups=0-AUJuc&groups=1-Z1VhpXp-1&measure=ZmimLJ

0.3% of citizens do not have access to Complete Kitchen Facilities
https://datausa.io/visualize?enlarged=c-lineplot-18rRP1-18SVoa-1&groups=0-18rRP1&groups=1-18SVoa-1&measure=Z7jTt2

**Comment by vbebo** [comment]
Sexually Transmitted Infections by State which is the number of newly diagnosed chlamydia cases per 100,000 population
Click on the magnifying glass to see the changes from 2014 - 2018
https://datausa.io/visualize?groups=0-z7J78&measure=2cp24R

**Comment by vbebo** [comment]
Office & Administrative Support Occupations is the most common jobs held by Native Hawaiian and Other Pacific Islander
https://datausa.io/visualize?groups=0-1dQe8s-7&groups=1-jKLTv&measure=1qWfo

(Closest I could get)

**Comment by davelandry** [comment]
@vbebo I would go to the deepest level, "Detailed Occupation", which shows that it's actually Cashiers!
https://datausa.io/visualize?groups=0-19hV1x&groups=1-1dQe8s-7&measure=1qWfo

**Comment by vbebo** [comment]
Dang, so close! Totally makes sense tho

**Comment by vbebo** [comment]
This last one is tricky. I even checked OEC and the usaspending.gov. Outside of just an ISP search, I got this:
https://datausa.io/visualize?groups=0-1pz0Cl-97&groups=1-EhDG6&groups=2-aLjg1-91&measure=1e64mv

**Comment by davelandry** [comment]
@vbebo dude, so close! The only difference I would make is to use the NAPCS classification for products (that's what we use in the product profiles): https://datausa.io/visualize?groups=0-1p90tp-61101&groups=1-EhDG6&groups=2-1pz0Cl-97&measure=1e64mv

well done!
