### ISSUE TITLE
Profiles with problems in jade

### ISSUE THREAD

**Issue by innerstage** [DataUSA/datausa-site#867]
The following profiles had problems displaying certain sections in `iron` and have been re-checked for problems in `jade`, most of them don't load:

- [x] https://jade.datausa.io/profile/university/brookline-college-albuquerque
- [x] https://jade.datausa.io/profile/university/in-session-arts-of-cosmetology-beauty-school
- [x] https://jade.datausa.io/profile/university/greater-lowell-technical-school
- [x] https://jade.datausa.io/profile/university/new-horizons-medical-institute-winder
- [x] https://jade.datausa.io/profile/university/academy-of-hair-design-pearl
- [x] https://jade.datausa.io/profile/university/ozarka-college
- [x] https://jade.datausa.io/profile/university/ogeechee-technical-college
- [x] https://jade.datausa.io/profile/university/indian-hills-community-college
- [x] https://jade.datausa.io/profile/university/ppg-technical-college
- [x] https://jade.datausa.io/profile/university/universal-technical-institute-of-texas-inc
- [x] https://jade.datausa.io/profile/university/refrigeration-school-inc
- [x] https://jade.datausa.io/profile/university/edic-college
- [x] https://jade.datausa.io/profile/university/northcentral-technical-college
- [x] https://jade.datausa.io/profile/university/cosmetology-college-of-franklin-county
- [x] https://jade.datausa.io/profile/university/hair-professionals-career-college-367981
- [x] https://jade.datausa.io/profile/university/eagle-gate-college-layton
- [x] https://jade.datausa.io/profile/university/the-salon-professional-academy-melbourne
- [x] https://jade.datausa.io/profile/university/itt-technical-institute-tempe
- [x] https://jade.datausa.io/profile/university/river-parishes-community-college (Check Enrollment section)
- [x] https://jade.datausa.io/profile/university/bryan-university
- [x] https://jade.datausa.io/profile/university/itt-technical-institute-greenville
- [x] https://jade.datausa.io/profile/university/menlo-college (Check Enrollment section)
- [x] https://jade.datausa.io/profile/university/shorter-university-college-of-adult-professional-programs
- [x] https://jade.datausa.io/profile/university/charles-of-italy-beauty-college
- [x] https://jade.datausa.io/profile/university/duluth-business-university

**Comment by davelandry** [comment]
Luckily all of these errors were based around only 2 bugs 😅

Some of the really small pages are littered with N/As, but we can save that scavanger hunt for another time (sometimes it's even better to show some N/As then to hide EVERYTHING)
