### ISSUE TITLE
add selectable Geomaps next to every LinePlot

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#874]
Add a Geomap visualization next to every LinePlot (duplicating the `"visualization topic-visualization"` class (that should hopefully keep the styles playing nice). Here are the requirements for the Geomap:
- [x] display the same dataset from the LinePlot on the Geomap (reference the Geomap configs at the bottom of the page for help)
- [x] add a `time` method to each so that we are initially viewing the most recent data, but have a `timeline` to scrub through the available times
- [x] add an onClick event to the geographies that, when clicked, modifies React state to:
  - [x] filter ALL LinePlot visualizations by that selected Geography
  - [x] highlights the `stroke` of that State in every Geomap

**Comment by jhmullen** [comment]
@davelandry available for review on `staging-covid`
