### ISSUE TITLE
setup cron job on both test servers to refresh the python script datasets

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#886]
we need to set up a cron job on the following servers, in this order (one at a time while they're not live):
- [x] acorn
- [x] banana
- [x] keyite

each server should have a cronjob that runs the following scripts every 3(?) hours:
 - `python jhcovid19.py`
 - `python mobilitycovid19.py`

You'll need to setup a python environment on the server in order to have the correct libraries from `requirements.txt` installed. @jspeiser was the last to do something like this on Data USA. So his caching bash scripts may be a good start (don't use their env though). I took a look at his bash script and already got started, this should hopefully be a good starting point:

```sh
#!/bin/sh
if [ -z "$STY" ]; then exec screen -dm -S "covid-data" /bin/bash "$0"; fi
. ~/Envs/datausa-site/bin/activate
python /home/deploy/datausa-site/jhcovid19.py
python /home/deploy/datausa-site/mobilitycovid19.py
```

**Comment by jhmullen** [comment]
@davelandry this is done on all three servers.
