### ISSUE TITLE
allow more combinatorial pairs in COVID cases section

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#892]
- [x] always display all 3 toggles (but disable them if they are not available given the selection)
- [x] allow "Per Capita" for Tests and Hospitalizations (I added  those variables to the data, `TestsPC` and `HospitalizationsPC`)
- [x] allow "Shift Time Axis" for ALL charts

**Comment by jhmullen** [comment]
@davelandry 

Pushed these changes to `staging` as requested
