### ISSUE TITLE
remove Rackspace load balancer

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#919]
1. review Rackspace Load Balancer configuration (be aware of separate http/https balancers)
2. change `datausa.io` DNS record to point to `keyite` IP address in Cloudflare
3. deactivate Rackspace load balancer and account

**Comment by mcastillomolina** [comment]
Update here: Im looking into a GCP alternative for rackspace [here](https://cloud.google.com/load-balancing/docs/https). This external load balancer provided by rackspace is what "keeps always alive" datausa site. If keyite goes down, it will automatically switch to lapis, but using the same external IP under datausa domain.

**Comment by davelandry** [comment]
@mcastillomolina you are overcomplicating the issue at hand here.

We have never truthfully used Rackspace as a load balancer, but as a solution to switch between staging and prod servers (before we had Cloudflare and Google Cloud).

So no alternative should be needed here at all, just change the DNS record in Cloudflare (see my notes above).

**Comment by mcastillomolina** [comment]
Yes, sorry for my misunderstood. I realized that as you said we are not using it as a load balancer. I'll proceed change the dns in cloudflare. However, I think that we could include a load balancer for our front end servers in the future, just to ensure that the site is always up
