### ISSUE TITLE
create new color and icon mapping for University sectors

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#958]
Current classifications: https://datausa.io/profile/geo/united-states#universities

New classification list: https://uranium-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJTZWN0b3IiLCJJUEVEUyBTZWN0b3IiLCJTZWN0b3IiXV0sImN1dHMiOltdLCJjdWJlIjoiaXBlZHNfY29tcGxldGlvbnMiLCJtZWFzdXJlcyI6WyJDb21wbGV0aW9ucyJdfQ==

**Comment by danaecatalan** [comment]
New color scale + icons:

#FAA34A    Public, 4-year or above
#8BC84D    Private not-for-profit, 4-year or above
#398059     Private for-profit, 4-year or above
#FF8166     Public, 2-year
#4CA3B6    Private not-for-profit, 2-year
#2C689B    Private for-profit, 2-year
#FFCD33    Public, less-than 2-year
#308984     Private not-for-profit, less-than 2-year
#453A8B    Private for-profit, less-than 2-year 

![Captura de pantalla 2022-02-04 a las 10 40 03](https://user-images.githubusercontent.com/23085310/152538527-cde293db-760e-4d28-bae8-d165458bf473.png)

Icons
![private](https://user-images.githubusercontent.com/23085310/152538728-f994f097-d695-45fc-a124-2ec86b579a86.svg)
![public](https://user-images.githubusercontent.com/23085310/152538730-e3827300-0fc7-470a-b652-262d496bd63a.svg)

**Comment by danaecatalan** [comment]
#FAA34A    Public, 4-year or above
#8BC84D    Private not-for-profit, 4-year or above
#398059     Private for-profit, 4-year or above
#FF8166     Public, 2-year
#4CA3B6    Private not-for-profit, 2-year
#2C689B    Private for-profit, 2-year
#FFCD33    Public, less-than 2-year
#308984     Private not-for-profit, less-than 2-year
#453A8B    Private for-profit, less-than 2-year
#AC4BAE    Administrative Unit 

![university sectors](https://user-images.githubusercontent.com/23085310/152563514-883cf2fe-723e-471a-987d-f8878e52213c.jpg)

the icon 
![administrative](https://user-images.githubusercontent.com/23085310/152563528-d2774716-e791-4c70-bd93-c57f3bfbb8fa.svg)

**Comment by davelandry** [comment]
@hermosillajelmy do you know how to hook this up in `app/d3plus.js`? want to send me a PR?

**Comment by hermosillajelmy** [comment]
@davelandry yes, i'm working on it
