### ISSUE TITLE
update d3plus dependencies

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#963]
<img width="999" alt="Screen Shot 2022-01-31 at 4 19 33 PM" src="https://user-images.githubusercontent.com/1847581/152818291-78444064-7f69-476a-8311-b1c0d70193cd.png">

:point_up_2: if you delete that highlighted block, save the file, and run npm i, it will detect that "it doesn't know which version of "d3plus-viz" to install, so it will install the latest

typically, when there's a d3plus update, there will often be a few packages that need to get updated (like in this case, d3plus-viz and d3plus-timeline)

so what I do when that happens, is just delete all d3 and d3plus dependencies from this file, and let npm i figure out which ones need to be updated

**Comment by hermosillajelmy** [comment]
@davelandry here is the [PR](https://github.com/DataUSA/datausa-site/pull/965), I hope I did well :crossed_fingers: Also, I added a new color category with sex for the profiles and keep the gender for the viz builder.
