### ISSUE TITLE
fix N/As in new Occupation profile content

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#993]

**Comment by alebjanes** [comment]
## Feedback Session 1:

### About

- [ ] Add year and source below the Stats. (Example: 2020 ACS 5-Year estimate)
- [ ] Maybe add the Similar Occupations paragraph (once it's fixed)

### Employment

**Employment Over Time**
- [ ] Add label to Y-axis and formatter to Y-axis ticks
- [ ] Remove Gender from tooltip
- [ ] Remove measure (Avg Wage or Workforce) from legend tooltip
- [ ] Evaluate adding `baseline: 0`
- [ ] Remove "workers" from paragraph
- [ ] Add values between parenthesis in growth paragraph (Example: "growth from 2014 (value) to 2020 (value)")
- [ ] Add a line in the chart to represent the total average wage
- [ ] Add second paragraph mentioning the difference between female and male wages

**Employment by Location**
- [ ] Add labels to selector (Level and Metric)
- [ ] Add a second paragraph for the Specialization option explaining what is this metric

**Yearly Wage Ranking**
- [ ] Fix second and second to last ranking labels (from "2" to "...")
- [ ] Change second paragraph to: The graph shows the ranking of _X occupation_ in relation to all _Detailed Occupations_
- [ ] Add # to ranking labels
- [ ] Change "Ranking Position" to "<Year> Rank" in tooltip
- [ ] In Major Occupations version: lower height of chart
- [ ] Add National Average Wage as a line (not a bar)

**Wage Distribution**
- [ ] Check if its still crashing when changing the selector
- [ ] Fix X-axis behavior when changing the selector
- [ ] Rotate X-axis labels (Add `rotation: true` in xConfig)

### General changes/fixes
- [ ] Similar occupations
- [ ] Add labels to selectors (Metric/Indicator, Grouping, Level, etc)
- [ ] Check Y-axis labels across all charts
