### ISSUE TITLE
first university About paragraph has "2016" hard-coded in the text

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-site#999]

**Comment by azapatam** [comment]
It's done! Now is a dynamic variable.

Before
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/42551166/191349880-90984537-506d-4483-a9d4-f4f8f8352ea6.png">

After
<img width="995" alt="image" src="https://user-images.githubusercontent.com/42551166/191350210-87f01c8d-21c2-43a5-a6fc-dff82b6c98d5.png">
